{
  "hash": "2fe7bb33014535512c4fc627492dbe73",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Examining Meta-Analysis\"\nauthor: [John Mount, Joseph Rickert]\ndate: \"2024-11-26\"\nformat: html\ncode-fold: true\ncode-summary: \"Show the code\"\nbibliography: references.bib\ndescription: \"In this post we would like to review the idea of *meta-analysis* and compare a traditional, frequentist style, random effects meta-analysis to Bayesian methods.\"\nfig-dpi: 300\nfig-align: \"center\"\nimage: plot.png\n---\n\n\n\nIn this post, we would like to review the idea of *meta-analysis* and compare a traditional, frequentist style, random effects meta-analysis to Bayesian methods. We will do this using the [meta](https://cran.r-project.org/package=meta) R package and a Bayesian analysis conducted with R but actually carried out by the [Stan](https://mc-stan.org/) programming language on the back end. We will use a small but interesting textbook data set of summary data from eight randomized controlled trials. These studies examined the effectiveness of the calcium channel blocker Amlodipine compared to a placebo in improving work capacity in patients with angina. The data set and the analysis with the `meta` package come directly from the textbook by @appliedmetawithR. Although there are several R packages that are capable of doing the Bayesian meta-analysis, we chose to work in [rstan](https://cran.r-project.org/package=rstan) to demonstrate its flexibility and hint how one might go about doing a large complex study that doesn't quite fit with pre-programmed paradigms.\n\nTo follow our examples, you really don't need to know much more about meta-analysis than the definition offered by @enwiki:1251112044: \"meta-analysis is a method of synthesis of quantitative data from multiple independent studies addressing a common research question\". If you want to dig deeper, a good overview of the goals and terminology can be found in @doi:10.2519/jospt.2011.3333. The online textbook [Doing Meta-Analysis in R: A Hands-on Guide](https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/) by @doingmetawithR will take you a long way in performing your own work.\n\n## Example\n\nLet's begin: load the required packages and read in the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlibrary(meta)\n\nangina <- read.csv(file = \"AmlodipineData.csv\",\n                   strip.white = TRUE,\n                   stringsAsFactors = FALSE)\n\nangina |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n| Protocol| nE|  meanE|   varE| nC|   meanC|   varC|\n|--------:|--:|------:|------:|--:|-------:|------:|\n|      154| 46| 0.2316| 0.2254| 48| -0.0027| 0.0007|\n|      156| 30| 0.2811| 0.1441| 26|  0.0270| 0.1139|\n|      157| 75| 0.1894| 0.1981| 72|  0.0443| 0.4972|\n|      162| 12| 0.0930| 0.1389| 12|  0.2277| 0.0488|\n|      163| 32| 0.1622| 0.0961| 34|  0.0056| 0.0955|\n|      166| 31| 0.1837| 0.1246| 31|  0.0943| 0.1734|\n|      303| 27| 0.6612| 0.7060| 27| -0.0057| 0.9891|\n|      306| 46| 0.1366| 0.1211| 47| -0.0057| 0.1291|\n\n\n:::\n:::\n\n\n\nThe data set contains eight rows, each representing the measured effects of treatment and control on different groups. The column definitions are:\n\n  * `Protocol` id number of the study the row is summarizing.\n  * `nE` number of patients in the treatment group.\n  * `meanE` mean treatment effect observed.\n  * `varE` variance of treatment effect observed.\n  * `nC` number of patients in the control group.\n  * `meanC` mean control effect observed.\n  * `varC` variance of control effect observed.\n  \n### Naive Pooling\n\nA [statistically inefficient](https://en.wikipedia.org/wiki/Efficiency_(statistics)), naive technique to combine the studies would be to pool all of the data. This is usually not even possible, as most studies don't share data --- and at best share summaries. We might hope this is enough to get a good estimate of the expected difference between treatment and non-treatment. However this ignores variance and treats low-quality results on the same footing as high-quality results, yielding unreliable results. Naive pooling also lacks standard diagnostic procedures and indications.\n\nThat being said, let's form the naive pooled estimate.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nsum(angina$nE * angina$meanE) / sum(angina$nE) - sum(angina$nC * angina$meanC) / sum(angina$nC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2012727\n```\n\n\n:::\n:::\n\n\n\n## A Fixed Effects Model\n\nPerhaps the simplest reliable analysis is the fixed effects model. The underlying assumption for the fixed-effects model is that the true underlying effect or difference between treatment and control, $\\delta$, is the same for all studies in the meta-analysis and that all possible risk factors are the same for all studies. Each study has its own observed effect size $\\hat{\\delta_i}$. However, each is assumed to be a noisy estimate of $\\delta$.\n\nSuch a study is summarized as follows.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nfixed.angina <- metacont(\n  nE, meanE, sqrt(varE),\n  nC, meanC, sqrt(varC),\n  data = angina,\n  study.lab = \"Protocol\",\n  random = FALSE)\n\nsummary(fixed.angina)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       MD            95%-CI %W(common)\n1  0.2343 [ 0.0969; 0.3717]       21.2\n2  0.2541 [ 0.0663; 0.4419]       11.4\n3  0.1451 [-0.0464; 0.3366]       10.9\n4 -0.1347 [-0.3798; 0.1104]        6.7\n5  0.1566 [ 0.0072; 0.3060]       17.9\n6  0.0894 [-0.1028; 0.2816]       10.8\n7  0.6669 [ 0.1758; 1.1580]        1.7\n8  0.1423 [-0.0015; 0.2861]       19.4\n\nNumber of studies: k = 8\nNumber of observations: o = 596 (o.e = 299, o.c = 297)\n\n                        MD           95%-CI    z  p-value\nCommon effect model 0.1619 [0.0986; 0.2252] 5.01 < 0.0001\n\nQuantifying heterogeneity (with 95%-CIs):\n tau^2 = 0.0001 [0.0000; 0.1667]; tau = 0.0116 [0.0000; 0.4082]\n I^2 = 43.2% [0.0%; 74.9%]; H = 1.33 [1.00; 2.00]\n\nTest of heterogeneity:\n     Q d.f. p-value\n 12.33    7  0.0902\n\nDetails of meta-analysis methods:\n- Inverse variance method\n- Restricted maximum-likelihood estimator for tau^2\n- Q-Profile method for confidence interval of tau^2 and tau\n- Calculation of I^2 based on Q\n```\n\n\n:::\n:::\n\n\n\nThe primary result of the summary is: the overall estimate for $\\delta$ is `0.1619`, much smaller than the naive pooling estimate of `0.2013`. Also, a number of diagnostics seem \"okay.\" From the forest plot, it is easy to see that the Amlodipine treatment is not statistically significant for four of the protocols, but the overall effect of the difference between the treatment and the control is statistically significant. The plot also shows the test for heterogeneity, which indicates that there is no evidence against homogeneity.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nmeta::forest(fixed.angina, layout = \"RevMan5\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=3000}\n:::\n:::\n\n\n\nNotice the fixed effects model is not the earlier naive mean; it is also not theoretically the same estimate as the random effects model, which we now discuss.\n\n## A Random Effects Model\n\nThe next level of modeling is a random effects model. In this style model, we admit that the studies may be, in fact, studying different populations and different effects. A perhaps cleaner way to think about this is not as a type of effect (fixed or random), but as a model structured as a hierarchy (@Gelman_Hill_2006). The idea is that the analyst claims the populations are related, and the different effects are drawn from a common distribution, and observations are then drawn from these *unobserved* per-population effects. Inference is possible as the observed outcomes distributionally constrain the unobserved parameters.\n\nThe underlying assumption for the random-effects model is that each study has its own true underlying treatment effect, $\\delta_i$, with variance ${\\sigma_i}^2$ that is estimated by $\\hat{\\delta_i}$ Furthermore, all of the $\\delta_i$ follow a $N(\\delta,\\tau^2)$ distribution. Hence,\n\n$$\n\\begin{align}\n\\hat{\\delta_i} &\\sim N(\\delta,\\sigma_i^2) \\\\\n\\delta_i &\\sim N(\\delta,\\tau^2)\n\\end{align}\n$$\n\n\n### Fit the Random-Effects Model\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nrandom.angina <- metacont(\n  nE, meanE, sqrt(varE),\n  nC, meanC, sqrt(varC),\n  data = angina,\n  study.lab = \"Protocol\",\n  random = TRUE)\nsummary(random.angina)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       MD            95%-CI %W(common) %W(random)\n1  0.2343 [ 0.0969; 0.3717]       21.2       21.1\n2  0.2541 [ 0.0663; 0.4419]       11.4       11.4\n3  0.1451 [-0.0464; 0.3366]       10.9       11.0\n4 -0.1347 [-0.3798; 0.1104]        6.7        6.7\n5  0.1566 [ 0.0072; 0.3060]       17.9       17.9\n6  0.0894 [-0.1028; 0.2816]       10.8       10.9\n7  0.6669 [ 0.1758; 1.1580]        1.7        1.7\n8  0.1423 [-0.0015; 0.2861]       19.4       19.3\n\nNumber of studies: k = 8\nNumber of observations: o = 596 (o.e = 299, o.c = 297)\n\n                         MD           95%-CI    z  p-value\nCommon effect model  0.1619 [0.0986; 0.2252] 5.01 < 0.0001\nRandom effects model 0.1617 [0.0978; 0.2257] 4.96 < 0.0001\n\nQuantifying heterogeneity (with 95%-CIs):\n tau^2 = 0.0001 [0.0000; 0.1667]; tau = 0.0116 [0.0000; 0.4082]\n I^2 = 43.2% [0.0%; 74.9%]; H = 1.33 [1.00; 2.00]\n\nTest of heterogeneity:\n     Q d.f. p-value\n 12.33    7  0.0902\n\nDetails of meta-analysis methods:\n- Inverse variance method\n- Restricted maximum-likelihood estimator for tau^2\n- Q-Profile method for confidence interval of tau^2 and tau\n- Calculation of I^2 based on Q\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nmeta::forest(random.angina, layout = \"RevMan5\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=3900}\n:::\n:::\n\n\n\nThe random effects result is a $\\delta$ estimate of about `0.1617`. In this case, not much different than the fixed effects estimate.\n\n## Issues\n\nSome issues associated with the above analyses include:\n\n  1) Limited control of the distributional assumptions. What if we wanted to assume specific distributions on the un-observed individual outcomes? What if we want to change assumptions for a sensitivity analysis?\n  2) The results are limited to point estimates of the distribution parameters.\n  3) The results may depend on the underlying assumption of Normal distributions of published summaries.\n  4) The reported significance is not necessarily the probability of positive effect for a new subject.\n\n### Bayesian analysis\n\nTo try and get direct control of the model, graphs, and the model explanation, we will perform a direct hierarchical analysis using Stan through the `rstan` package.\n\nWe want to estimate the unobserved true value of treatment effect by a meta-analysis of different studies. The challenges of meta-analysis include:\n\n  * The studies may be of somewhat different populations, implying different mean and variance of treatment and control response.\n  * We are working from summary data from the studies and not data on individual patients.\n\nWe are going to make things simple for the analyst and ask only for approximate distributional assumptions on the individual respondents in terms of unknown, to-be-inferred parameters. Then we will use Stan to sample individual patient outcomes (and unobserved parameters) that are biased to be consistent with the known summaries. This saves having to know or assume distributions of the summary statistics. And, in fact, we could try individual distributions different from the \"Normal\" we plug in here.\n\nThe advantage of working this way is that the modeling assumptions are explicitly visible and controllable. The matching downside is that we have to own our modeling assumptions; we lose the anonymity of the implicit justification of invoking tradition and recognized authorities.\n\nTo get this to work, we use two Stan tricks or patterns:\n\n  * Instantiate many intermediate variables (such as individual effects).\n  * Simulate equality enforcement by saying a specified difference tends to be small.\n\nFirst, load the required packages.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# attach packages\nlibrary(ggplot2)\nlibrary(rstan)\nlibrary(digest)\nsource(\"define_Stan_model.R\")\n```\n:::\n\n\n\nAnd then prepare the study names for display.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_studies = nrow(angina)\n# make strings for later use\ndescriptions = vapply(\n  seq(n_studies),\n  function(i) { paste0(\n    'Protocol ', angina[i, 'Protocol'], ' (',\n    'nE=', angina[i, 'nE'], ', meanE=', angina[i, 'meanE'],\n    ', nC=', angina[i, 'nC'], ', meanC=', angina[i, 'meanC'],\n    ')') },\n  character(1))\n```\n:::\n\n\n\nThe modeling principles are as follows:\n\n  * There are unobserved true treatment and control effects we want to estimate. Call these $\\mu^{treatment}$ and $\\mu^{control}$. We assume a shared standard deviation $\\sigma$. We can easily model without a shared standard deviation by introducing more parameters to the model specification.\n  * For each protocol or study, we have ideal unobserved mean treatment effects and mean control effects. Call these $\\mu_{i}^{treatment}$ and $\\mu_{i}^{control}$ for $i = 1 \\cdots 8$.\n\nThe equations bringing each study $i$ into our Bayesian model are as follows. \n\n\n\\begin{align}\n\\mu^{treatment}_i &\\sim N(\\mu^{treatment}, \\sigma^2) &\\# \\; \\mu^{treatment} \\; \\text{is what we are trying to infer} \\\\\n\\mu^{control}_i &\\sim N(\\mu^{control}, \\sigma^2) &\\# \\; \\mu^{control} \\;\\text{is what we are trying to infer} \\\\\n\nsubject^{treatment}_{i,j} &\\sim N(\\mu^{treatment}_i, \\sigma_i^2) &\\# \\; \\text{unobserved} \\\\\nsubject^{control}_{i,j} &\\sim N(\\mu^{control}_i, \\sigma_i^2) &\\# \\; \\text{unobserved} \\\\\n\nmean_j(subject^{treatment}_{i,j}) - observed\\_mean^{treatment}_{i} &\\sim N(0, 0.01) &\\# \\; \\text{force inferred to be near observed} \\\\\nmean_j(subject^{control}_{i,j}) - observed\\_mean^{control}_{i} &\\sim N(0, 0.01) &\\# \\; \\text{force inferred near to be observed} \\\\\nvar_j(subject^{treatment}_{i,j}) - observed\\_var^{treatment}_{i} &\\sim N(0, 0.01) &\\# \\; \\text{force inferred to be near observed} \\\\\nvar_j(subject^{control}_{i,j}) - observed\\_var^{control}_{i} &\\sim N(0, 0.01) &\\# \\; \\text{force inferred near to be observed}\n\\end{align}\n\n\nThe above equations are designed to be argued over. They need to be believed to relate the unobserved true treatment and control effects to the recorded study summaries. If they are not believed, is there a correction that would fix that? If the equations are good enough, then we can sample the implied posterior distribution of the unknown true treatment and control effects, which would finish the meta-analysis. The driving idea is that it may be easier to discuss how unobserved individual measurements may relate to observed and unobserved summaries and parameters than to work out how to relate statistical summaries to statistical summaries.\n\nIt is mechanical to translate the above relations into a Stan source model to make the desired inferences. The lines marked \"force inferred to be near observed\" are not distributional beliefs- but just a tool for enforcing that the inferred individual data should match the claimed summary statistics. \n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# the Stan data\nstan_data = list(\n  n_studies = n_studies,\n  nE = array(angina$nE, dim = n_studies),  # deal with length 1 arrays confused with scalars in JSON path\n  meanE = array(angina$meanE, dim = n_studies),\n  varE = array(angina$varE, dim = n_studies), \n  nC = array(angina$nC, dim = n_studies), \n  meanC = array(angina$meanC, dim = n_studies), \n  varC = array(angina$varC, dim = n_studies))\n```\n:::\n\n\n\nHere we define the Stan Model.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nanalysis_src_joint <- define_Stan_model(n_studies = n_studies, c_replacement = '')\n```\n:::\n\n\n\nThis code runs the procedure. The function `run_cache()` runs the standard `stan()` function, saving the result to a file cache for quick and deterministic re-re-renderings of the notebook. The caching is not required, but the runs took about five minutes on an old-Intel based Mac.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# run the sampling procedure\nfit_joint <- run_cached(\n  stan,\n  list(\n  model_code = analysis_src_joint,  # Stan program\n  data = stan_data,                 # named list of data\n  chains = 4,                       # number of Markov chains\n  warmup = 2000,                    # number of warm up iterations per chain\n  iter = 4000,                      # total number of iterations per chain\n  cores = 4,                        # number of cores (could use one per chain)\n  refresh = 0,                      # no progress shown\n  pars = c(\"lp__\",                  # parameters to bring back\n           \"inferred_grand_treatment_mean\", \n           \"inferred_grand_control_mean\", \n           \"inferred_between_group_stddev\",\n           \"inferred_group_treatment_mean\", \n           \"inferred_group_control_mean\",\n           \"inferred_in_group_stddev\", \n           \"sampled_meanE\", \n           \"sampled_varE\",\n           \"sampled_meanC\", \n           \"sampled_varC\")\n  ),\n  prefix = \"Amlodipine_joint\"\n)\n```\n:::\n\n\n\nAnd then, we extract the results.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# show primary inference\ninference <- fit_joint |>\n  as.data.frame() |>\n  (`[`)(c(\"inferred_grand_treatment_mean\", \"inferred_grand_control_mean\", \"inferred_between_group_stddev\")) |>\n  colMeans() |>\n  as.list() |>\n  data.frame() \ninference['delta'] <- inference['inferred_grand_treatment_mean'] - inference['inferred_grand_control_mean']\n\ninference |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n| inferred_grand_treatment_mean| inferred_grand_control_mean| inferred_between_group_stddev|     delta|\n|-----------------------------:|---------------------------:|-----------------------------:|---------:|\n|                     0.2002917|                   0.0391202|                     0.0650105| 0.1611715|\n\n\n:::\n:::\n\n\n\nAnd our new estimate is: 0.1611715 which is very similar to the previous results. We can graph the inferred posterior distribution of effect size as follows.\n\nFirst, we plot the estimated posterior distribution of both the treatment and control effects. This is the final result of the analysis, using all of the data, simulated from the eight trials. In this result, high-variance studies have a diminished influence on the overall estimated effect sizes. Running all of the simulated data together without maintaining the trial structure would produce an inflated `0.2` again.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# plot the grand group inferences \ndual_density_plot(\n  fit_joint, \n  c1 = 'inferred_grand_treatment_mean', \n  c2 = 'inferred_grand_control_mean',\n  title = 'grand estimate')\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=2100}\n:::\n:::\n\n\n\n### Watching the Pooling\n\nWe can examine how the hierarchical model changes the estimates as follows. In each case we are plotting the posterior distribution of the unknown treatment and control effect estimates, this time per original study, with and without pooling analysis.\n\nTo do this, we define an additional \"the studies are unrelated model\".\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nanalysis_src_independent <- define_Stan_model(n_studies = n_studies, c_replacement = '//')\n```\n:::\n\n\n\nWe then fit the model or use previously cached results.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# run the sampling procedure\nfit_independent <- run_cached(\n  stan,\n  list(\n  model_code = analysis_src_independent,  # Stan program\n  data = stan_data,                       # named list of data\n  chains = 4,                             # number of Markov chains\n  warmup = 2000,                          # number of warm up iterations per chain\n  iter = 4000,                            # total number of iterations per chain\n  cores = 4,                              # number of cores (could use one per chain)\n  refresh = 0,                            # no progress shown\n  pars = c(\"lp__\",                        # parameters to bring back\n           \"inferred_group_treatment_mean\", \n           \"inferred_group_control_mean\",\n           \"inferred_in_group_stddev\", \n           \"sampled_meanE\", \n           \"sampled_varE\",\n           \"sampled_meanC\",\n           \"sampled_varC\")\n  ),\n  prefix = \"Amlodipine_independent\"\n)\n```\n:::\n\n\n\nThen, we can plot the compared inferences of the hierarchical and independent models.\n\nThe top plot shows the Bayesian inference that would result using only data from a single study. The bottom plot shows the estimate made for the given study, given the data from the other studies. Notice that in this first pair of plots, the bottom plot sharpens the distributions and tends to pull the means together. The first two plots have the means pulled in, the third pushed out, and behavior varies by group from then on. Notice in Protocol 162, the inferred means are reversed. These graphs are the Bayesian analogs of the forest plots above.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# plot comparison inferences\nfor(i in seq(n_studies)) {\n  print(double_dual_density_plot(\n    fitA = fit_independent,\n    fitB = fit_joint,\n    c1 = gsub('{i}', as.character(i), 'inferred_group_treatment_mean[{i}]', fixed = TRUE), \n    c2 = gsub('{i}', as.character(i), 'inferred_group_control_mean[{i}]', fixed = TRUE), \n    title = gsub('{p}', descriptions[[i]], '{p}\\nestimates', fixed = TRUE),\n    vlines=c(angina[i, 'meanE'], angina[i, 'meanC'])))\n}\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=2100}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-2.png){width=2100}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-3.png){width=2100}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-4.png){width=2100}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-5.png){width=2100}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-6.png){width=2100}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-7.png){width=2100}\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-8.png){width=2100}\n:::\n:::\n\n\n\n\n## Conclusion\n\nIt is a challenge to communicate exactly *what* meta-analysis a given standard package actually implements. It is our assumption that many standard meta-analyses reflect the tools available to the researchers and do not necessarily provide the ability to implement distributions that reflect the modeling assumptions they would prefer. Or, to be blunt, you don't really know what the packaged models are doing until you can match them to a known calculation.\n\nPerhaps the greatest difference between the \"standard\" and Bayesian approaches is that Bayesian modeling requires the analyst to really *own* the modeling assumptions. This is why we wrote out so many of the modeling distributional assumptions as formulas instead of as named methodologies in our method descriptions.\n\nWe feel that there is a gap in the available practical literature. There is room for more teaching materials making meta-analysis more approachable by relating them to explicit model structures.\n\n\n## References\n\n::: {#refs}\n:::\n\n## Appendix: Reproducing the Result\n\nThe files required to reproduce the result are:\n\n  1) **[ExaminingMetaAnalysis.qmd](https://github.com/r-community-works/rworks-website/blob/main/posts/meta-analysis/index.qmd)**: this notebook.\n  2) **[AmlodipineData.csv](AmlodipineData.csv)**: the original data.\n  3) **[define_Stan_model.R](define_Stan_model.R)**: helper functions.\n  4) (optional) **[cache_Amlodipine_independent_b818d8db720377f42b728cbc88a94e58.RDS](cache_Amlodipine_independent_b818d8db720377f42b728cbc88a94e58.RDS)**: the cached result.\n  5) (optional) **[cache_Amlodipine_joint_f0ae8de9e99d9396a5f2a21f5638030f.RDS](cache_Amlodipine_joint_f0ae8de9e99d9396a5f2a21f5638030f.RDS)**: the cached result.\n  \n---\n\n## Comments {.unlisted}\n\n\n\n{{< bluesky-comments https://bsky.app/profile/rworks.bsky.social/post/3lckxpwwzss2u >}}\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}