{
  "hash": "991b133412eb67e9681b6d2140ff1bfa",
  "result": {
    "markdown": "---\ntitle: \"Stage II OSCC — Health Economics Model\"\nsubtitle: \"Analysis from the patient's perspective\"\nauthor: \"Joseph Rickert\"\ndate: 2026-03-25\ndescription: \"This post presents a proof of concept for Healthcare Economics Models constructed from a patient's perspective. Using inputs derived from the literature, it builds an eight state continuous time Markov chain to construct a synthetic cohort of patients undergoing treatment for stage II squamous cell carcinoma. The total expected time in each treatment health state for two treatment arms are computed and paired with EQ-5D utilities derived from the literature. The resulting model presents the QALYs associated with each treatment arm. It is envisioned that future models of this sort, constructed under the supervision of physicians and health care professionals, would be useful to clinicians both in documenting the treatment decision process and in communicating with patients.\"\neditor: source\nformat: html\n---\n\n\n\nMost health care economics models are constructed from the perspective of a managed health care system such as those offered in Canada and several European countries, or from the perspective of some other third party such as an insurance company. Although the benefits of constructing models from the patient's perspective have been discussed in the literature, see for example [Ioannidis & Garber (2011)](https://pmc.ncbi.nlm.nih.gov/articles/PMC3134464/) and [Tai et al. (2016)](https://pubmed.ncbi.nlm.nih.gov/27712720/), few models have been published. Obvious reasons for this situation would include the privacy issues associated with obtaining patient specific data and the apparent lack of economic incentives to commit resources required to abstract individual patient trajectories from patient level data models.\n\nThis post explores the hypothesis that detailed, data-driven, patient-specific models may not be necessary in order to achieve most of the benefits of a health economics model from the patients perspective. I present a lightweight, cohort model that I believe captures the majority of the benefits to both physicians and patients that might result from a patient focused model.\n\nThe model is intended to be a proof of concept, a minimal viable model that may be useful to physicians both in deciding on treatment options and in informing patients about the potential outcomes and how they may experience these outcomes. To see how the medical literature may be helpful for this kind of modeling I explore the specific case of choosing between surgery and definitive radiation therapy for patients with stage II oral squamous cell carcinoma (OSCC). \n\n**Note that the model developed here is not being presented as a medical analysis. No medical experts have been consulted in its construction. It is merely being offered as an example of what could be done to build a health care economics model from a patient's perspective with today's modeling tools. Also note that I made significant use of [Posit Assistant](https://posit.co/blog/introducing-ai-in-rstudio/) for the RStudio IDE configured with Claude Sonnet 4.6 which I found to be immensely helpful both for code construction and literature searches even though utility of the latter use was limited by the vexing proclivity of Claude to hallucinate. **\n\n\n\n\n## Overview of the Model\n\nThe model begins with the decision to select radiation or surgery and identifies eight health states that patient will pass through. The states visited and the order of visiting them depend on the initial decision. The next step uses the theory of continuous time Markov chains (CTMC) to construct a synthetic data set for a cohort of patients who vary in age and tumor size. The CTMC model is driven by The estimates for the jump-chain transition probabilities and mean state occupancy times. I have chosen this approach because I believe that these quantities will have intuitive appeal to clinicians and medical experts. I have attempted to abstract reasonable estimates for these parameters from the medical literature. If done correctly, these sorts of abstracted estimates should be helpful as default parameters which clinicians could change based on their experience and intuition. \n\nThe key insight here is that the synthetic data set is the underlying statistical model. Empirical survival curves and the time spent in each state and other useful quantities are then calculated from the synthetic data. The patient specific healthcare model is then constructed by estimating the utility of each health state to the patient. This is accomplished by constructing quality adjust life years (QALYs) based on [EQ-5D](https://www.ncbi.nlm.nih.gov/books/NBK565680/) values reported in the literature. \n\n## Continuous Time Markov Chain Simulation\n\nThis section builds a synthetic patient cohort for Stage II (T2 N0 M0) oral\nsquamous cell carcinoma using a continuous-time Markov chain (CTMC). The\nsimulation is driven by two clinician-interpret able inputs:\n\n- **Jump chain probabilities** `jump_P[i,j]`: given that a patient *leaves*\n  state *i*, the probability they transition directly to state *j*.\n- **Mean sojourn times** `mean_sojourn[i]`: the average time (months) a patient\n  spends in state *i* before transitioning.\n\nThe sources for these quantities are identified by comments in the code. The complete references for these sources are given in the Reference section below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Packages used throughout the post\"}\nlibrary(ggplot2)\nlibrary(grid)\nlibrary(dplyr)\nlibrary(msm)\nlibrary(gt)\n```\n:::\n\n\n\n### State Diagram\n\nIt is my understanding that although most patients wit stage II OSCC are treated with surgery there are times when surgery is either not possible or not preferable and the in these exceptional cases, radiation treatment is the primary alternative. The following state diagram is an attempt to abstract both the health states a patient will experience following treatment and the probable paths that will be taken among them. Eight states seemed to me to be the minimum number of states required to represent the complexities of treatment.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# library(ggplot2)\n# library(grid)\n\nBG <- \"#F0F3F7\"\n\n# ── 1. Nodes ─────────────────────────────────────────────────────────────────\n# Layout: left=initial treatment, center=adjuvant/NED, right=outcomes/death\nnodes <- data.frame(\n  id    = 1:8,\n  label = c(\n    \"S1\\nSurgery\\n± Neck Dissection\",\n    \"S2\\nDefinitive\\nRadiation\",\n    \"S3\\nPost-op\\nSurveillance\",\n    \"S4\\nAdjuvant RT\\n(PORT)\",\n    \"S5\\nAdjuvant\\nChemoRT (POCRT)\",\n    \"S6\\nNED\\n(Health)\",\n    \"S7\\nLocoregional\\nRecurrence\",\n    \"S8\\nDeath\"\n  ),\n  x    = c(1.5,  1.5,  4.5,  4.5,  4.5,  7.0,  9.5,  11.5),\n  y    = c(8.5,  3.0,  9.5,  6.5,  3.5,  6.5,  7.5,   5.5),\n  fill = c(\"#E67E22\",\"#8E44AD\",\"#F39C12\",\"#2980B9\",\"#16A085\",\n           \"#27AE60\",\"#C0392B\",\"#2C3E50\"),\n  stringsAsFactors = FALSE\n)\n\n# ── 2. Edge definitions: from, to, label, curvature, nudge_x, nudge_y ────────\nedge_defs <- list(\n  # Surgery → downstream\n  c(1, 3,  \"No high-risk\\nfeatures\",    0.00,  0.10,  0.30),\n  c(1, 4,  \"High-risk:\\nmargins/PNI/\\nLVI/nodes\",  0.10, -0.20,  0.20),\n  c(1, 5,  \"ECE/pos\\nmargins\",          0.18,  0.00, -0.30),\n  c(1, 8,  \"Peri-op\\ndeath\",           -0.22,  0.10, -0.20),\n  # Definitive RT → downstream\n  c(2, 6,  \"NED\",                       0.18,  0.00,  0.25),\n  c(2, 7,  \"Treatment\\nfailure\",        0.00,  0.00,  0.25),\n  c(2, 8,  \"Death\",                     0.14, -0.10, -0.20),\n  # Post-op Surveillance → downstream\n  c(3, 6,  \"\",                          0.00,  0.10,  0.25),\n  c(3, 7,  \"\",                          0.22,  0.20, -0.10),\n  c(3, 8,  \"\",                         -0.18,  0.10, -0.18),\n  # PORT → downstream\n  c(4, 6,  \"\",                          0.00,  0.10,  0.25),\n  c(4, 7,  \"\",                          0.12,  0.10,  0.18),\n  c(4, 8,  \"\",                          0.14,  0.10, -0.18),\n  # POCRT → downstream\n  c(5, 6,  \"\",                          0.00,  0.10,  0.25),\n  c(5, 7,  \"\",                          0.00,  0.10,  0.22),\n  c(5, 8,  \"\",                          0.12,  0.10, -0.18),\n  # NED → outcomes\n  c(6, 7,  \"LR recurrence\",             0.00, -0.10,  0.25),\n  c(6, 8,  \"Death\",                     0.18,  0.10, -0.14),\n  # Locoregional Recurrence → outcomes\n  c(7, 8,  \"Death\",                     0.00,  0.00,  0.25),\n  c(7, 6,  \"Salvage\\nsuccess\",         -0.28, -0.28,  0.00)\n)\n\nedges <- do.call(rbind, lapply(edge_defs, function(r) {\n  data.frame(from=as.integer(r[[1]]), to=as.integer(r[[2]]),\n             prob=r[[3]], curvature=as.numeric(r[[4]]),\n             nudge_x=as.numeric(r[[5]]), nudge_y=as.numeric(r[[6]]),\n             stringsAsFactors=FALSE)\n}))\n\n# Attach node coordinates\nedges <- merge(edges, nodes[, c(\"id\",\"x\",\"y\")], by.x=\"from\", by.y=\"id\", sort=FALSE)\nnames(edges)[names(edges)==\"x\"] <- \"x0\"; names(edges)[names(edges)==\"y\"] <- \"y0\"\nedges <- merge(edges, nodes[, c(\"id\",\"x\",\"y\",\"fill\")], by.x=\"to\", by.y=\"id\", sort=FALSE)\nnames(edges)[names(edges)==\"x\"] <- \"x1\"; names(edges)[names(edges)==\"y\"] <- \"y1\"\nnames(edges)[names(edges)==\"fill\"] <- \"dest_col\"\n\n# Shorten endpoints to node perimeter\nNODE_R <- 0.58\nshorten <- function(x0,y0,x1,y1,r) {\n  dx<-x1-x0; dy<-y1-y0; d<-sqrt(dx^2+dy^2)\n  list(xs=x0+dx*r/d, ys=y0+dy*r/d, xe=x1-dx*r/d, ye=y1-dy*r/d)\n}\nsegs     <- Map(shorten, edges$x0, edges$y0, edges$x1, edges$y1, MoreArgs=list(r=NODE_R))\nedges$xs <- sapply(segs,`[[`,\"xs\"); edges$ys <- sapply(segs,`[[`,\"ys\")\nedges$xe <- sapply(segs,`[[`,\"xe\"); edges$ye <- sapply(segs,`[[`,\"ye\")\nedges$lx <- (edges$xs+edges$xe)/2 + edges$nudge_x\nedges$ly <- (edges$ys+edges$ye)/2 + edges$nudge_y\n\n# ── 3. Build layers ───────────────────────────────────────────────────────────\narrow_layers <- lapply(seq_len(nrow(edges)), function(i) {\n  e <- edges[i,,drop=FALSE]\n  geom_curve(data=e, mapping=aes(x=xs,y=ys,xend=xe,yend=ye),\n             curvature=e$curvature[[1]], colour=e$dest_col[[1]],\n             linewidth=1.0, alpha=0.80,\n             arrow=arrow(length=unit(9,\"pt\"), type=\"closed\", ends=\"last\"),\n             show.legend=FALSE)\n})\n\nlabel_layers <- lapply(seq_len(nrow(edges)), function(i) {\n  e <- edges[i,,drop=FALSE]\n  if (nchar(trimws(e$prob[[1]])) == 0) return(NULL)\n  geom_label(data=e, mapping=aes(x=lx,y=ly,label=prob),\n             colour=e$dest_col[[1]], fill=BG, size=2.6, fontface=\"bold\",\n             label.size=0.22, label.r=unit(0.10,\"lines\"),\n             label.padding=unit(0.15,\"lines\"), show.legend=FALSE)\n})\nlabel_layers <- Filter(Negate(is.null), label_layers)\n\n# ── 4. Base plot ──────────────────────────────────────────────────────────────\nbase_plot <- ggplot() +\n  theme_void(base_size=10) +\n  theme(\n    plot.background  = element_rect(fill=BG, colour=NA),\n    panel.background = element_rect(fill=BG, colour=NA),\n    plot.title  = element_text(family=\"serif\", face=\"bold\", size=16,\n                               colour=\"#1A2535\", hjust=0.5, margin=margin(b=4)),\n    plot.subtitle = element_text(size=9, colour=\"#555555\", hjust=0.5,\n                                 margin=margin(b=10))\n  ) +\n  coord_fixed(xlim=c(0, 13), ylim=c(1.5, 11), clip=\"off\") +\n  labs(title=\"Stage II Oral Squamous Cell Carcinoma\",\n       subtitle=\"CTMC State Transition Diagram\")\n\n# ── 5. Assemble ───────────────────────────────────────────────────────────────\nall_layers <- c(arrow_layers, label_layers,\n  list(\n    # Column labels\n    annotate(\"text\", x=1.5,  y=10.8, label=\"Initial\\nTreatment\",\n             size=3.2, colour=\"#555\", fontface=\"italic\", hjust=0.5),\n    annotate(\"text\", x=4.5,  y=10.8, label=\"Post-surgical\\nPathway\",\n             size=3.2, colour=\"#555\", fontface=\"italic\", hjust=0.5),\n    annotate(\"text\", x=7.0,  y=10.8, label=\"No Evidence\\nof Disease\",\n             size=3.2, colour=\"#555\", fontface=\"italic\", hjust=0.5),\n    annotate(\"text\", x=9.5,  y=10.8, label=\"Disease\\nProgression\",\n             size=3.2, colour=\"#555\", fontface=\"italic\", hjust=0.5),\n    annotate(\"text\", x=11.5, y=10.8, label=\"Absorbing\\nState\",\n             size=3.2, colour=\"#555\", fontface=\"italic\", hjust=0.5),\n    # Nodes\n    geom_point(data=nodes, aes(x=x, y=y, colour=fill),\n               size=28, show.legend=FALSE),\n    scale_colour_identity(),\n    geom_text(data=nodes, aes(x=x, y=y, label=label),\n              colour=\"white\", size=2.8, fontface=\"bold\", lineheight=0.9),\n    # Surgical candidate bracket\n    annotate(\"segment\", x=0.25, xend=0.25, y=2.2, yend=9.3,\n             colour=\"#888\", linewidth=0.5),\n    annotate(\"segment\", x=0.25, xend=0.45, y=9.3, yend=9.3,\n             colour=\"#888\", linewidth=0.5),\n    annotate(\"segment\", x=0.25, xend=0.45, y=2.2, yend=2.2,\n             colour=\"#888\", linewidth=0.5),\n    annotate(\"text\", x=0.0, y=5.75, label=\"Surgical\\ncandidate?\\nYes ↑\\nNo ↓\",\n             size=2.8, colour=\"#666\", hjust=0.5, lineheight=0.9)\n  )\n)\n\nReduce(\"+\", all_layers, init=base_plot)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n\n| State | Label                   | Role                                              |\n|-------|-------------------------|---------------------------------------------------|\n| S1    | Surgery                 | Initial surgical treatment (days–weeks)           |\n| S2    | DefinitiveRT            | Non-surgical candidates; 6–7 week RT course       |\n| S3    | PostOpSurveillance      | Surgery, no high-risk pathological features       |\n| S4    | AdjuvantRT (PORT)       | High-risk: margins, PNI, LVI, multiple nodes      |\n| S5    | AdjuvantChemoRT (POCRT) | Highest-risk: ECE or positive margins             |\n| S6    | NED                     | No evidence of disease; long-term surveillance    |\n| S7    | LR Recurrence           | Locoregional recurrence at primary or nodes       |\n| S8    | Death                   | Absorbing state                                   |\n\n\n## Data Simulation\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Simulation setup\"}\nset.seed(6413)\n\nN_PATIENTS <- 400\nMAX_TIME   <- 60      # months (5-year follow-up)\nobs_base   <- c(0, 1, 2, 3, 6, 9, 12, 18, 24, 36, 48, 60)\n\nstate_labels_ii <- c(\n  \"Surgery\", \"DefinitiveRT\", \"PostOpSurveillance\",\n  \"AdjuvantRT_PORT\", \"AdjuvantChemoRT_POCRT\",\n  \"NED\", \"LR_Recurrence\", \"Death\"\n)\n\n# ── Patient covariates ────────────────────────────────────────────────────────\n# Stage II OSCC (T2 N0 M0): tumor 2-4 cm, DOI 5-10 mm\nage           <- as.integer(round(rnorm(N_PATIENTS, mean = 62, sd = 11)))\nage           <- pmax(32L, pmin(85L, age))\ntumor_size_cm <- round(runif(N_PATIENTS, 2.0, 4.0), 1)\nDOI_mm        <- round(runif(N_PATIENTS, 5.0, 10.0), 1)\n\n# Surgical candidacy: logistic model, ~78% surgery at age 60\nsurgery_prob <- plogis(1.5 - 0.04 * (age - 60))\ntreatment    <- ifelse(runif(N_PATIENTS) < surgery_prob, \"Surgery\", \"DefinitiveRT\")\n```\n:::\n\n\n### Clinician Inputs\n\nA continuous time Markov chain may be described by its jump chain and transition rate matrix. The jump chain may be thought of as an embedded discrete time Markov chain that gives the probabilities of which state the chain will jump to next when it is time to jump. The transition rates are mean rates at which of the probability distributions that determine when jumps will be made. The major assumption in this model is that the jump probabilities and the times that patients are likely to spend in each state which are inverted to obtain the transition rates will be intuitive to most practicing physicians. The values for these parameters have been derived from the literature, however, the model has been set up so that they can be easily changed if the physician disagrees with the with the values in general or thinks that a particular class of patients would be better represented by other values. The justifications for the default values for the parameters driving the model are provided in the comments in the code and in the references below.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Clinician inputs: jump probabilities and mean sojourn times\"}\n# == CLINICIAN INPUTS ==========================================================\n#\n# jump_P[i, j]  : probability of moving to state j *given* a transition occurs\n#                 from state i.  Rows must sum to 1 for states 1-7.\n#\n# mean_sojourn  : average time (months) in each transient state.\n#\n# Together these fully specify the CTMC generator:\n#   Q[i, j] = jump_P[i, j] / mean_sojourn[i]   (off-diagonal)\n# All downstream simulation code derives Q_base automatically from these inputs.\n\n# ── Jump chain transition probabilities ───────────────────────────────────────\n\n\njump_P <- matrix(0, 8, 8,\n  dimnames = list(paste0(\"S\", 1:8), paste0(\"S\", 1:8)))\n\n# S1 (Surgery) -> {S3=no high-risk, S4=PORT, S5=POCRT, S8=peri-op death}\n# ~20-30% high-risk features -> PORT (Tassone et al. 2023, NCDB n=53,503; DOI:10.1002/ohn.205)\n# ~10-15% ECE/pos margins -> POCRT; peri-operative mortality ~1-2% (Nathan et al. 2025, NSQIP n=866; DOI:10.18203/issn.2454-5929.ijohns20252980)\n# NB: S8 revised from 0.05 to 0.015 — the original 5% exceeded the literature range of 1-2%;\n# freed mass (0.035) reallocated to S3 (residual no-adjuvant group), S4 and S5 unchanged.\njump_P[1, c(3, 4, 5, 8)] <- c(0.585, 0.25, 0.15, 0.015)\n\n# S2 (DefinitiveRT) -> {S6=NED, S7=treatment failure, S8=death}\n# Definitive RT alone locoregional control ~65% for T2N0M0 (Dana-Farber Group 2011 PMID 21531515, 2-yr LRC 64%; Studer et al. 2007 T2-4 LC ~50-60%)\njump_P[2, c(6, 7, 8)] <- c(0.65, 0.28, 0.07)\n\n# S3 (PostOpSurveillance) -> {S6=NED, S7=LR recurrence, S8=death}\n# 5-yr LR recurrence ~12-18% after margin-negative R0 surgery alone (Ord 2006 15.5%; Luryi 2014 NCDB early-stage series)\njump_P[3, c(6, 7, 8)] <- c(0.74, 0.18, 0.08)\n\n# S4 (PORT) -> {S6=NED, S7=LR recurrence, S8=death}\n# After PORT, 3-yr OS ~71% (95% CI 67-75%) in adjuvant PORT cohort (Hosni et al. 2019, PMID: 30244160)\njump_P[4, c(6, 7, 8)] <- c(0.67, 0.23, 0.10)\n\n# S5 (POCRT) -> {S6=NED, S7=LR recurrence, S8=death}\n# After POCRT, locoregional control ~60%; Stage II mortality revised down to 10% (Bernier 2004, Cooper 2004; Stage II subgroup)\njump_P[5, c(6, 7, 8)] <- c(0.60, 0.30, 0.10)\n\n# S6 (NED) -> {S7=LR recurrence, S8=death}\n# ~75% leave NED via recurrence vs other-cause death (SEER Stage II split)\njump_P[6, c(7, 8)] <- c(0.75, 0.25)\n\n# S7 (LR Recurrence) -> {S6=salvage success, S8=death}\n# Salvage success 0.43 / mortality 0.57: Lee et al. 2024 pooled 5-yr OS = 43% (n=2069); revised from c(0.25, 0.75) — previous value over-estimated post-recurrence mortality\njump_P[7, c(6, 8)] <- c(0.43, 0.57)\n\n# ── Mean sojourn times (months) ───────────────────────────────────────────────\nmean_sojourn <- c(\n  1.5,   # S1  Surgery: weighted mean accounting for real-world S-PORT delays ~8-9 wks (Correia 2026; Dayan 2023; Graboyes 2017)\n  3.0,   # S2  DefinitiveRT: RT course (1.5 mo) + post-RT response assessment window >=12 wks (NCCN HNC Guidelines; Mehanna et al. 2016 [PET-NECK] PMID 26958921)\n  22.0,  # S3  PostOpSurveillance: weighted mean to event (NED@24mo x0.74 + recur@18mo x0.18 + death@14mo x0.08) = 22 mo (Blatt 2022; Brands 2019; Ord 2006)\n  3.0,   # S4  PORT: ~6-week adjuvant RT + recovery — supported, unchanged\n  4.0,   # S5  POCRT: ~6-week concurrent chemoRT + extended recovery — supported, unchanged\n  120.0, # S6  NED: calibrated to SEER ~20% 5-yr recurrence; exit rate 0.0083/mo -> mean 120 mo (SEER localized OCC; Brands 2019; Luryi 2014)\n  12.5,  # S7  LR Recurrence: median OS ~12-18 mo all-comers (Liu 2007; Contrera 2022) — within supported range, unchanged\n  NA     # S8  Death (absorbing)\n)\nnames(mean_sojourn) <- paste0(\"S\", 1:8)\n\n# == END CLINICIAN INPUTS ======================================================\n\n# ── Derive Q_base from clinician inputs ───────────────────────────────────────\n# Q[i,j] = jump_P[i,j] / mean_sojourn[i]\nQ_base <- matrix(0, 8, 8)\nfor (i in 1:7) {\n  for (j in which(jump_P[i, ] > 0)) {\n    Q_base[i, j] <- jump_P[i, j] / mean_sojourn[i]\n  }\n}\ndiag(Q_base) <- -rowSums(Q_base)\n```\n:::\n\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n\n\n##### Jump Chain Transition Probabilities\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nas.data.frame(jump_P)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   S1 S2    S3   S4   S5   S6   S7    S8\nS1  0  0 0.585 0.25 0.15 0.00 0.00 0.015\nS2  0  0 0.000 0.00 0.00 0.65 0.28 0.070\nS3  0  0 0.000 0.00 0.00 0.74 0.18 0.080\nS4  0  0 0.000 0.00 0.00 0.67 0.23 0.100\nS5  0  0 0.000 0.00 0.00 0.60 0.30 0.100\nS6  0  0 0.000 0.00 0.00 0.00 0.75 0.250\nS7  0  0 0.000 0.00 0.00 0.43 0.00 0.570\nS8  0  0 0.000 0.00 0.00 0.00 0.00 0.000\n```\n:::\n:::\n\n\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"45%\"}\n\n\n\n##### Mean Sojourn Times and Implied Rates\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\ndata.frame(\n  #State        = paste0(\"S\", 1:7),\n  Label        = state_labels_ii[1:7],\n  Mean_sojourn = mean_sojourn[1:7],\n  Total_rate   = round(-diag(Q_base)[1:7], 4)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                   Label Mean_sojourn Total_rate\nS1               Surgery          1.5     0.6667\nS2          DefinitiveRT          3.0     0.3333\nS3    PostOpSurveillance         22.0     0.0455\nS4       AdjuvantRT_PORT          3.0     0.3333\nS5 AdjuvantChemoRT_POCRT          4.0     0.2500\nS6                   NED        120.0     0.0083\nS7         LR_Recurrence         12.5     0.0800\n```\n:::\n:::\n\n\n:::\n\n::::\n\n\n### Synthetic Data\n\nHere are the first few rows of the synthetic data set. Note that two covariates: age of patient and tumor size are included.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"show code\"}\n# ── Patient-specific Q (covariates scale recurrence & mortality rates) ─────────\nmake_Q <- function(age_i, size_i) {\n  Q <- Q_base\n  age_eff  <- exp(0.025 * (age_i  - 60))   # older  -> higher mortality\n  size_eff <- exp(0.180 * (size_i -  3.0))  # larger -> higher recurrence\n  Q[3, 7] <- Q_base[3, 7] * size_eff        # PostOpSurv -> LR Recurrence\n  Q[6, 7] <- Q_base[6, 7] * size_eff * age_eff\n  Q[6, 8] <- Q_base[6, 8] * age_eff\n  Q[7, 8] <- Q_base[7, 8] * age_eff\n  diag(Q) <- 0\n  diag(Q) <- -rowSums(Q)\n  Q\n}\n\n# ── Simulate one patient's full CTMC path ─────────────────────────────────────\nsim_ctmc <- function(init_s, Q_i, max_t) {\n  t_vec <- 0; s_vec <- init_s; s <- init_s; t <- 0\n  while (t < max_t && s != 8L) {\n    total_rate <- -Q_i[s, s]\n    if (total_rate == 0) break\n    t <- t + rexp(1L, total_rate)\n    if (t > max_t) break\n    probs    <- pmax(Q_i[s, ], 0)\n    probs[s] <- 0\n    s        <- sample.int(8L, 1L, prob = probs)\n    t_vec    <- c(t_vec, t); s_vec <- c(s_vec, s)\n  }\n  list(times = t_vec, states = s_vec)\n}\n\n# State at a given observation time (last known state)\nstate_at <- function(traj, obs_t) {\n  traj$states[max(which(traj$times <= obs_t))]\n}\n\n# ── Generate panel data ────────────────────────────────────────────────────────\nrecords <- vector(\"list\", N_PATIENTS)\n\nfor (i in seq_len(N_PATIENTS)) {\n  init_s  <- if (treatment[i] == \"Surgery\") 1L else 2L\n  Q_i     <- make_Q(age[i], tumor_size_cm[i])\n  traj    <- sim_ctmc(init_s, Q_i, MAX_TIME)\n\n  jitter  <- c(0, runif(length(obs_base) - 1L, -0.5, 0.5))\n  obs_t   <- sort(unique(pmax(0, obs_base + jitter)))\n\n  death_t <- if (8L %in% traj$states)\n    traj$times[which(traj$states == 8L)[1L]]\n  else Inf\n\n  obs_t <- obs_t[obs_t < death_t]\n  if (is.finite(death_t) && death_t <= MAX_TIME)\n    obs_t <- c(obs_t, death_t)\n\n  obs_s <- sapply(obs_t, state_at, traj = traj)\n\n  records[[i]] <- data.frame(\n    id            = i,\n    time          = round(obs_t, 2),\n    state         = obs_s,\n    age           = age[i],\n    tumor_size_cm = tumor_size_cm[i],\n    DOI_mm        = DOI_mm[i],\n    treatment     = treatment[i],\n    stringsAsFactors = FALSE\n  )\n}\n\noscc2_data <- do.call(rbind, records)\nrownames(oscc2_data) <- NULL\noscc2_data$state_label <- state_labels_ii[oscc2_data$state]\n\n# Save synthetic data\nwrite.csv(oscc2_data, \"OSCC_HE_Synthetic_Data.csv\", row.names = FALSE)\n\n# First 10 rows\nhead(oscc2_data, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   id time state age tumor_size_cm DOI_mm treatment        state_label\n1   1 0.00     1  59           3.7    9.5   Surgery            Surgery\n2   1 0.64     1  59           3.7    9.5   Surgery            Surgery\n3   1 1.60     1  59           3.7    9.5   Surgery            Surgery\n4   1 3.14     1  59           3.7    9.5   Surgery            Surgery\n5   1 6.10     4  59           3.7    9.5   Surgery    AdjuvantRT_PORT\n6   1 6.13     8  59           3.7    9.5   Surgery              Death\n7   2 0.00     1  50           4.0    7.9   Surgery            Surgery\n8   2 1.27     3  50           4.0    7.9   Surgery PostOpSurveillance\n9   2 2.26     3  50           4.0    7.9   Surgery PostOpSurveillance\n10  2 3.02     3  50           4.0    7.9   Surgery PostOpSurveillance\n```\n:::\n:::\n\n\n---\n\n### Summary of Data Set\n\nThis table shows some of the meta-data describing the synthetic data set.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Cohort summary\"}\n# Collect components for footnotes\ntrt_counts <- table(treatment)\ndied <- oscc2_data |>\n  dplyr::filter(state == 8) |>\n  dplyr::distinct(id) |>\n  nrow()\n\n# Main table: state visit counts\nas.data.frame(table(State = oscc2_data$state_label)) |>\n  gt() |>\n  cols_label(State = \"State\", Freq = \"Observations\") |>\n  tab_source_note(md(paste0(\n    \"**Dataset:** \", nrow(oscc2_data), \" observations; \",\n    N_PATIENTS, \" patients\"\n  ))) |>\n  tab_source_note(md(paste0(\n    \"**Treatment:** Surgery = \", trt_counts[\"Surgery\"],\n    \"; DefinitiveRT = \", trt_counts[\"DefinitiveRT\"]\n  ))) |>\n  tab_source_note(md(paste0(\n    \"**Mortality:** \", died, \" / \", N_PATIENTS,\n    \" patients reached Death (\",\n    round(100 * died / N_PATIENTS, 1), \"%)\"\n  )))\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"yabchgroau\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yabchgroau table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yabchgroau thead, #yabchgroau tbody, #yabchgroau tfoot, #yabchgroau tr, #yabchgroau td, #yabchgroau th {\n  border-style: none;\n}\n\n#yabchgroau p {\n  margin: 0;\n  padding: 0;\n}\n\n#yabchgroau .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yabchgroau .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yabchgroau .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yabchgroau .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yabchgroau .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yabchgroau .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yabchgroau .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yabchgroau .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yabchgroau .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yabchgroau .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yabchgroau .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yabchgroau .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yabchgroau .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yabchgroau .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yabchgroau .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yabchgroau .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yabchgroau .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yabchgroau .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yabchgroau .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yabchgroau .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yabchgroau .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yabchgroau .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yabchgroau .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yabchgroau .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yabchgroau .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yabchgroau .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yabchgroau .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yabchgroau .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yabchgroau .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yabchgroau .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yabchgroau .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yabchgroau .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yabchgroau .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yabchgroau .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yabchgroau .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yabchgroau .gt_left {\n  text-align: left;\n}\n\n#yabchgroau .gt_center {\n  text-align: center;\n}\n\n#yabchgroau .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yabchgroau .gt_font_normal {\n  font-weight: normal;\n}\n\n#yabchgroau .gt_font_bold {\n  font-weight: bold;\n}\n\n#yabchgroau .gt_font_italic {\n  font-style: italic;\n}\n\n#yabchgroau .gt_super {\n  font-size: 65%;\n}\n\n#yabchgroau .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yabchgroau .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yabchgroau .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yabchgroau .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yabchgroau .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yabchgroau .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yabchgroau .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yabchgroau .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yabchgroau div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"State\">State</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Freq\">Observations</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"State\" class=\"gt_row gt_center\">AdjuvantChemoRT_POCRT</td>\n<td headers=\"Freq\" class=\"gt_row gt_right\">87</td></tr>\n    <tr><td headers=\"State\" class=\"gt_row gt_center\">AdjuvantRT_PORT</td>\n<td headers=\"Freq\" class=\"gt_row gt_right\">159</td></tr>\n    <tr><td headers=\"State\" class=\"gt_row gt_center\">Death</td>\n<td headers=\"Freq\" class=\"gt_row gt_right\">161</td></tr>\n    <tr><td headers=\"State\" class=\"gt_row gt_center\">DefinitiveRT</td>\n<td headers=\"Freq\" class=\"gt_row gt_right\">239</td></tr>\n    <tr><td headers=\"State\" class=\"gt_row gt_center\">LR_Recurrence</td>\n<td headers=\"Freq\" class=\"gt_row gt_right\">298</td></tr>\n    <tr><td headers=\"State\" class=\"gt_row gt_center\">NED</td>\n<td headers=\"Freq\" class=\"gt_row gt_right\">1736</td></tr>\n    <tr><td headers=\"State\" class=\"gt_row gt_center\">PostOpSurveillance</td>\n<td headers=\"Freq\" class=\"gt_row gt_right\">961</td></tr>\n    <tr><td headers=\"State\" class=\"gt_row gt_center\">Surgery</td>\n<td headers=\"Freq\" class=\"gt_row gt_right\">611</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"2\"><span data-qmd-base64=\"PHN0cm9uZz5EYXRhc2V0Ojwvc3Ryb25nPiA0MjUyIG9ic2VydmF0aW9uczsgNDAwIHBhdGllbnRz\"><span class='gt_from_md'><strong>Dataset:</strong> 4252 observations; 400 patients</span></span></td>\n    </tr>\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"2\"><span data-qmd-base64=\"PHN0cm9uZz5UcmVhdG1lbnQ6PC9zdHJvbmc+IFN1cmdlcnkgPSAzMTM7IERlZmluaXRpdmVSVCA9IDg3\"><span class='gt_from_md'><strong>Treatment:</strong> Surgery = 313; DefinitiveRT = 87</span></span></td>\n    </tr>\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"2\"><span data-qmd-base64=\"PHN0cm9uZz5Nb3J0YWxpdHk6PC9zdHJvbmc+IDE2MSAvIDQwMCBwYXRpZW50cyByZWFjaGVkIERlYXRoICg0MC4yJSk=\"><span class='gt_from_md'><strong>Mortality:</strong> 161 / 400 patients reached Death (40.2%)</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n:::\n:::\n\n### First Patient Trajectory\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show trajectory\"}\noscc2_data[oscc2_data$id == 1,\n           c(\"id\", \"time\", \"state\", \"state_label\", \"treatment\",\n             \"age\", \"tumor_size_cm\", \"DOI_mm\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  id time state     state_label treatment age tumor_size_cm DOI_mm\n1  1 0.00     1         Surgery   Surgery  59           3.7    9.5\n2  1 0.64     1         Surgery   Surgery  59           3.7    9.5\n3  1 1.60     1         Surgery   Surgery  59           3.7    9.5\n4  1 3.14     1         Surgery   Surgery  59           3.7    9.5\n5  1 6.10     4 AdjuvantRT_PORT   Surgery  59           3.7    9.5\n6  1 6.13     8           Death   Surgery  59           3.7    9.5\n```\n:::\n:::\n\n\n\n---\n\n## Survival Analysis\n\n### Overall Survival\n\nThe first plot shows overall survival (Kaplan-Meier) curves for patients in both treatment arms and the overall survival curves for the individual survival curves. Note that, as I believe would be expected, surgery exhibits a slightly better overall survival curve (Approximately 73% vs approximately 65% at 5 years). However, both curves show very good five year survival probabilities. \n\n\nThree external benchmark points are overlaid on the Kaplan–Meier curves as filled diamonds. \n\n* Siegel et al. (2024) report approximately 84% five-year *relative* survival for localised oral cavity cancer in SEER (diagnoses 2013–2019); adjusting for background mortality at a median age of approximately 62 years using the SSA 2021 Period Life Table yields an estimated absolute five-year OS of ~77%, shown here against the Surgery arm curve. See the 5 year adjustment note below.\n* Hosni et al. (2019) observed a three-year OS of 71% (95% CI 67–75%) in 601 OSCC patients receiving adjuvant PORT at Princess Margaret Cancer Centre, also plotted against the Surgery arm. \n* Sher et al. (2011) reported a two-year OS of 63% in 12 oral cavity patients treated with definitive IMRT at Dana-Farber Cancer Institute, shown against the Definitive RT arm. \n\n\n\n\nThe second plot panel shows the overall survival curves by treatment for each of the four possible values of the covariates.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Kaplan-Meier survival curves\"}\nlibrary(survival)\nlibrary(survminer)\n\n# One row per patient: time to death or end of follow-up\nkm_input <- oscc2_data |>\n  dplyr::group_by(id, treatment) |>\n  dplyr::summarise(\n    time  = max(time),\n    event = as.integer(any(state == 8)),\n    .groups = \"drop\"\n  )\n\nkm_fit_2arm <- survfit(Surv(time, event) ~ treatment, data = km_input)\n\nkm_plot <- ggsurvplot(\n  km_fit_2arm,\n  data        = km_input,\n  conf.int    = FALSE,\n  risk.table  = TRUE,\n  palette     = c(\"#D55E00\", \"#0072B2\"),   # DefinitiveRT=orange, Surgery=blue (alphabetical strata order)\n  legend.labs = c(\"Definitive RT\", \"Surgery\"),\n  xlab        = \"Time (months)\",\n  ylab        = \"Survival probability\",\n  title       = \"Overall Survival — Stage II OSCC\",\n  ylim        = c(0.25, 1),\n  ggtheme     = theme_bw()\n)\n\n# Overlay external benchmark points (diamonds) on the KM plot\nkm_plot$plot <- km_plot$plot +\n  annotate(\"point\", x = 60, y = 0.77, shape = 23, size = 4,\n           fill = \"#0072B2\", color = \"black\") +\n  annotate(\"text\",  x = 60, y = 0.77,\n           label = \"Siegel 2024\\n(SEER ~77%)\", vjust = -0.35, hjust = 0.5, size = 2.8) +\n  annotate(\"point\", x = 36, y = 0.71, shape = 23, size = 4,\n           fill = \"#0072B2\", color = \"black\") +\n  annotate(\"text\",  x = 36, y = 0.71,\n           label = \"Hosni 2019\\n(71% at 3 yr)\", vjust = -0.35, hjust = 0.5, size = 2.8) +\n  annotate(\"point\", x = 24, y = 0.63, shape = 23, size = 4,\n           fill = \"#D55E00\", color = \"black\") +\n  annotate(\"text\",  x = 24, y = 0.63,\n           label = \"Sher 2011\\n(63% at 2 yr)\", vjust = 1.6, hjust = 0.5, size = 2.8)\n\nkm_plot\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n\n\n### Survival by Age and Tumour Size\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"KM curves stratified by age × tumour size\"}\nlibrary(broom)\nlibrary(ggplot2)\nlibrary(dplyr)\n\n# ── One row per patient with covariate categories ─────────────────────────────\n# Age split at 62 (simulation mean); tumour size split at 3 cm (Stage II midpoint)\nkm_cov <- oscc2_data |>\n  dplyr::group_by(id, treatment) |>\n  dplyr::summarise(\n    time          = max(time),\n    event         = as.integer(any(state == 8)),\n    age           = first(age),\n    tumor_size_cm = first(tumor_size_cm),\n    .groups       = \"drop\"\n  ) |>\n  dplyr::mutate(\n    age_grp  = factor(ifelse(age  < 62,  \"Age < 62\",   \"Age ≥ 62\"),\n                      levels = c(\"Age < 62\", \"Age ≥ 62\")),\n    size_grp = factor(ifelse(tumor_size_cm < 3.0, \"Tumour < 3 cm\", \"Tumour ≥ 3 cm\"),\n                      levels = c(\"Tumour < 3 cm\", \"Tumour ≥ 3 cm\")),\n    covariate_group = factor(\n      interaction(age_grp, size_grp, sep = \", \"),\n      levels = c(\n        \"Age < 62, Tumour < 3 cm\",\n        \"Age < 62, Tumour ≥ 3 cm\",\n        \"Age ≥ 62, Tumour < 3 cm\",\n        \"Age ≥ 62, Tumour ≥ 3 cm\"\n      )\n    )\n  )\n\npal4  <- c(\"#2166AC\", \"#92C5DE\", \"#D6604D\", \"#B2182B\")\nlabs4 <- c(\"Age < 62, Tumour < 3 cm\",\n           \"Age < 62, Tumour ≥ 3 cm\",\n           \"Age ≥ 62, Tumour < 3 cm\",\n           \"Age ≥ 62, Tumour ≥ 3 cm\")\n\n# ── Tidy survival estimates per arm ──────────────────────────────────────────\ntidy_arm <- function(arm, data) {\n  df  <- dplyr::filter(data, treatment == arm)\n  fit <- survfit(Surv(time, event) ~ covariate_group, data = df)\n  broom::tidy(fit, conf.int = FALSE) |>\n    dplyr::mutate(\n      treatment = arm,\n      covariate_group = factor(\n        sub(\"covariate_group=\", \"\", strata),\n        levels = levels(data$covariate_group)\n      )\n    )\n}\n\nsurv_tidy <- dplyr::bind_rows(\n  tidy_arm(\"Surgery\",      km_cov),\n  tidy_arm(\"DefinitiveRT\", km_cov)\n) |>\n  dplyr::mutate(treatment = factor(treatment,\n    levels = c(\"Surgery\", \"DefinitiveRT\"),\n    labels = c(\"Surgery Arm\", \"Definitive RT Arm\")))\n\n# ── Two-panel KM plot ─────────────────────────────────────────────────────────\nggplot(surv_tidy, aes(x = time, y = estimate,\n                      colour = covariate_group,\n                      group  = covariate_group)) +\n  geom_step(linewidth = 0.8) +\n  facet_wrap(~treatment, ncol = 2) +\n  scale_colour_manual(values = pal4, labels = labs4) +\n  scale_y_continuous(labels = scales::percent_format(accuracy = 1),\n                     limits = c(0, 1), breaks = seq(0, 1, 0.25)) +\n  scale_x_continuous(limits = c(0, 60), breaks = seq(0, 60, 12)) +\n  labs(\n    x      = \"Time (months)\",\n    y      = \"Survival probability\",\n    colour = \"Age / Tumour Size\",\n    title  = \"Overall Survival by Age and Tumour Size — Stage II OSCC\"\n  ) +\n  theme_bw(base_size = 11) +\n  theme(\n    legend.position  = \"bottom\",\n    legend.direction = \"horizontal\",\n    legend.text      = element_text(size = 9),\n    legend.title     = element_text(size = 10, face = \"bold\"),\n    strip.text       = element_text(size = 11, face = \"bold\"),\n    plot.title       = element_text(size = 12, face = \"bold\")\n  ) +\n  guides(colour = guide_legend(nrow = 2, byrow = TRUE))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n---\n\n### What the curves show:\n\n::: {.cell}\n\n:::\n\n* **Surgery arm** (n = 313): age is the dominant predictor of survival.\n  The youngest, smallest-tumour subgroup (Age < 62, Tumour < 3 cm; dark blue) reaches\n  64% at 5 years, while the youngest with larger tumours (Age < 62,\n  Tumour ≥ 3 cm; light blue) reaches 67% — an ordering that likely\n  reflects sampling variation in the synthetic cohort rather than a true protective\n  effect of tumour size.\n  Among older patients (Age ≥ 62), those with smaller tumours (Tumour < 3 cm; orange)\n  fare worst at 61%, while those with larger tumours (dark red) reach\n  50%, again with the caveat that synthetic-data variation can invert the\n  expected size effect within age strata.\n\n* **Definitive RT arm** (n = 87): the four subgroups together contain only\n  87 patients, yielding wide confidence bands and coarse staircase steps;\n  point estimates (67%, 67%, 42%, 58%\n  for the dark-blue, light-blue, orange, and dark-red subgroups respectively) should\n  be interpreted with caution. The broad pattern mirrors the Surgery arm — older age\n  is associated with lower survival — but the small-n instability makes subgroup\n  comparisons across treatment arms unreliable.\n\nNote that the covariate effects are encoded in the `make_Q` function used to create the synthetic data as follows:\n\n  * `age_eff  <- exp(0.025 * (age_i  - 60))   # older  -> higher mortality`\n  * `size_eff <- exp(0.180 * (size_i -  3.0))  # larger -> higher recurrence`\n\n\n### Progression-Free Survival\n\nProgression-free survival (PFS) is defined here as the time from treatment start to the first occurrence of either locoregional recurrence (S7) or death (S8), whichever comes first. Patients who reached neither endpoint by month 60 are censored at their last observed time.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Progression-free survival — Kaplan-Meier with at-risk table\"}\nlibrary(survival)\nlibrary(survminer)\n\n# ── Build per-patient PFS endpoint ───────────────────────────────────────────\n# Event = first entry into LR_Recurrence (state 7) or Death (state 8)\npfs_events <- oscc2_data |>\n  dplyr::filter(state %in% c(7L, 8L)) |>\n  dplyr::group_by(id) |>\n  dplyr::slice_min(time, n = 1, with_ties = FALSE) |>\n  dplyr::ungroup() |>\n  dplyr::select(id, pfs_time = time, pfs_event_type = state_label)\n\nlast_obs <- oscc2_data |>\n  dplyr::group_by(id) |>\n  dplyr::slice_max(time, n = 1, with_ties = FALSE) |>\n  dplyr::ungroup() |>\n  dplyr::select(id, last_time = time, treatment)\n\npfs_df <- last_obs |>\n  dplyr::left_join(pfs_events, by = \"id\") |>\n  dplyr::mutate(\n    pfs_time  = dplyr::coalesce(pfs_time, last_time),\n    pfs_event = as.integer(!is.na(pfs_event_type))\n  )\n\n# ── Fit KM curves ─────────────────────────────────────────────────────────────\nkm_pfs <- survfit(Surv(pfs_time, pfs_event) ~ treatment, data = pfs_df)\nkm_pfs_named <- km_pfs\nnames(km_pfs_named$strata) <- c(\"Definitive RT\", \"Surgery\")\n\n# ── Plot with at-risk table ───────────────────────────────────────────────────\nggsurvplot(\n  km_pfs_named,\n  data              = pfs_df,\n  palette           = c(\"#D55E00\", \"#0072B2\"),\n  conf.int          = TRUE,\n  conf.int.alpha    = 0.15,\n  size              = 0.9,\n  risk.table        = TRUE,\n  risk.table.col    = \"strata\",\n  risk.table.height = 0.25,\n  tables.theme      = theme_cleantable(),\n  xlab              = \"Time (months)\",\n  ylab              = \"Progression-free probability\",\n  title             = \"Progression-Free Survival — Stage II OSCC\",\n  legend.title      = \"Treatment\",\n  legend.labs       = c(\"Definitive RT\", \"Surgery\"),\n  legend            = \"bottom\",\n  surv.median.line  = \"hv\",\n  break.time.by     = 12,\n  xlim              = c(0, 60),\n  ylim              = c(0, 1),\n  ggtheme           = theme_minimal(base_size = 13),\n  fontsize          = 4\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n#### PFS at key timepoints\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"PFS estimates at 12, 24, 36, 48, 60 months\"}\ntbl_fun <- function(s) {\n  data.frame(\n    Treatment = as.character(s$strata),\n    Time      = s$time,\n    PFS       = round(s$surv,  3),\n    Lower95   = round(s$lower, 3),\n    Upper95   = round(s$upper, 3)\n  )\n}\ntbl_fun(summary(km_pfs_named, times = c(12, 24, 36, 48, 60))) |>\n  knitr::kable(\n    col.names = c(\"Treatment\", \"Month\", \"PFS\", \"95% CI lower\", \"95% CI upper\"),\n    caption   = \"Kaplan-Meier PFS estimates at annual checkpoints\"\n  )\n```\n\n::: {.cell-output-display}\nTable: Kaplan-Meier PFS estimates at annual checkpoints\n\n|Treatment     | Month|   PFS| 95% CI lower| 95% CI upper|\n|:-------------|-----:|-----:|------------:|------------:|\n|Definitive RT |    12| 0.655|        0.563|        0.763|\n|Definitive RT |    24| 0.540|        0.445|        0.656|\n|Definitive RT |    36| 0.506|        0.411|        0.623|\n|Definitive RT |    48| 0.460|        0.366|        0.577|\n|Definitive RT |    60| 0.400|        0.309|        0.518|\n|Surgery       |    12| 0.799|        0.756|        0.844|\n|Surgery       |    24| 0.700|        0.651|        0.752|\n|Surgery       |    36| 0.623|        0.572|        0.679|\n|Surgery       |    48| 0.553|        0.500|        0.611|\n|Surgery       |    60| 0.500|        0.447|        0.558|\n:::\n:::\n\n::: {.cell}\n\n:::\n\n#### What the PFS curves show\n\n* Surgery achieves notably higher early PFS: approximately 80% at 12 months versus 66% for Definitive RT — a 14 percentage point difference driven by the higher probability of early locoregional treatment failure in the RT arm.\n* The gap narrows progressively over the 60-month horizon, with Surgery at 50% and Definitive RT at 40% at month 60.\n* The wider confidence band on the Definitive RT curve reflects the smaller sample size in that arm.\n* **Interpretation note:** because `oscc2_data` is synthetic data generated from the model's own transition probabilities, these PFS curves are an internal consistency check rather than independent clinical calibration data.\n\n## Time Patients Spend in Each Health State\n\nThe total times that patients are expected to spend in each state over a 60-month horizon drive the economics analysis. The ability to make this calculation is the primary motivation for modeling the treatment regimen as a continuous time Markov chain.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"State occupancy function\"}\nlibrary(expm)\n\n# Adapted from plot_msm_state_occupancy() (Breast_Cancer_v3.qmd).\n# Accepts Q_base directly instead of a fitted msm model, and accepts\n# a start_state argument so the two treatment arms can be compared.\nplot_state_occupancy <- function(Q,\n                                 start_state  = 1,\n                                 tmax         = 60,\n                                 tstep        = 0.5,\n                                 state_labels = NULL,\n                                 title        = \"State Occupancy Probabilities\") {\n  n_states    <- nrow(Q)\n  start_probs <- rep(0, n_states)\n  start_probs[start_state] <- 1\n  time <- seq(0, tmax, by = tstep)\n\n  occ <- matrix(NA, nrow = length(time), ncol = n_states)\n  colnames(occ) <- paste0(\"S\", seq_len(n_states))\n  for (i in seq_along(time))\n    occ[i, ] <- start_probs %*% expm(Q * time[i])\n\n  df_long <- as.data.frame(occ) |>\n    dplyr::mutate(time = time) |>\n    tidyr::pivot_longer(-time, names_to = \"state\", values_to = \"prob\")\n\n  if (!is.null(state_labels))\n    df_long$state <- factor(df_long$state,\n      levels = paste0(\"S\", seq_len(n_states)),\n      labels = state_labels)\n\n  ggplot(df_long, aes(x = time, y = prob, colour = state)) +\n    geom_line(linewidth = 1.0) +\n    labs(x = \"Time (months)\", y = \"Probability\",\n         title = title, colour = \"State\") +\n    theme_bw(base_size = 12)\n}\n\n# Expected time in each state: trapezoid integral of P(t) over 0-60 months\ncompute_state_time <- function(Q, start_state, tmax = 60, tstep = 0.5) {\n  n_states    <- nrow(Q)\n  start_probs <- rep(0, n_states)\n  start_probs[start_state] <- 1\n  time <- seq(0, tmax, by = tstep)\n  occ  <- matrix(NA, nrow = length(time), ncol = n_states)\n  for (i in seq_along(time))\n    occ[i, ] <- start_probs %*% expm(Q * time[i])\n  apply(occ, 2, function(p)\n    sum(diff(time) * (p[-1] + p[-length(p)]) / 2))\n}\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Expected state time by arm\"}\ntime_surg <- compute_state_time(Q_base, start_state = 1)\ntime_def  <- compute_state_time(Q_base, start_state = 2)\n\ndata.frame(\n  State      = paste0(\"S\", 1:8),\n  Label      = state_labels_ii,\n  Surgery_mo = round(time_surg, 2),\n  DefRT_mo   = round(time_def,  2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  State                 Label Surgery_mo DefRT_mo\n1    S1               Surgery       1.51     0.00\n2    S2          DefinitiveRT       0.00     3.01\n3    S3    PostOpSurveillance      11.96     0.00\n4    S4       AdjuvantRT_PORT       0.75     0.00\n5    S5 AdjuvantChemoRT_POCRT       0.60     0.00\n6    S6                   NED      28.83    35.54\n7    S7         LR_Recurrence       4.09     5.67\n8    S8                 Death      12.26    15.78\n```\n:::\n:::\n\nThe state occupancy plots show the probability of being in each state as time progresses. For both plots, focusing on a particular time point gives a gives an estimate of a patient's probable health state.\n\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\n#### State Occupancy: Surgery \n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Surgery arm occupancy plot\"}\nplot_state_occupancy(\n  Q            = Q_base,\n  start_state  = 1,\n  state_labels = state_labels_ii,\n  title        = \"State Occupancy Probabilities — Surgery Arm\"\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n:::\n\n::: {.column width=\"10%\"}\n\n:::\n\n::: {.column width=\"45%\"}\n\n#### State Occupancy: Definitive RT \n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Definitive RT arm occupancy plot\"}\nplot_state_occupancy(\n  Q            = Q_base,\n  start_state  = 2,\n  state_labels = state_labels_ii,\n  title        = \"State Occupancy Probabilities — Definitive RT Arm\"\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n:::\n\n::::\n\n---\n\n\n\n## Health Economic Evaluation — Patient Perspective\n\nThe health Economics model presented here focus on QALYs calculated with with help of EQ-5D utilities. Although the utilities are abstractions without meaning to most patients they do provide a measure, however imperfect, of how \"on average\" others with the same disease have rated the ensemble of unpleasant experiences related to each possible health state. To be truly helpful physicians and their care teams need tell the story surrounding each state explaining the side effects of the treatments experienced in each health state along with the strategies that previous patients have employed to cope with them.\n\nThe model does not calculate costs under the assumption that, in most cases, cost would not be directly relevant to patients. Moreover in the United States, such calculations would be impossible. The U.S. health care system is set up so that the cost of treatments are only made known to patients after the treatments have be received.\n\n### Quality-Adjusted Life Years (QALYs)\n\nA Quality-Adjusted Life Year (QALY) combines the quantity and quality of life\ninto a single metric. One QALY represents one year lived in perfect health;\na year spent in a health state with diminished quality counts for less than\none QALY in proportion to that state's utility weight.\n\nIn this model, QALYs are calculated in three steps:\n\n1. **Assign utility weights.** Each of the eight health states is assigned\n   an EQ-5D utility value between 0 (death) and 1 (perfect health), drawn\n   from peer-reviewed literature on head-and-neck cancer patients.\n\n2. **Estimate time in each state.** The continuous-time Markov chain (CTMC)\n   simulation provides the expected number of months the cohort spends in\n   each state over a 60-month horizon, separately for the Surgery arm and\n   the Definitive Radiation Therapy arm.\n\n3. **Compute utility-weighted life years.** For each state, the time (in months)\n   is multiplied by its utility weight and the products are summed across all\n   states. Dividing by 12 converts the result to years:\n\n$$\n\\text{Total QALYs} = \\frac{1}{12} \\sum_{i=1}^{8} \\text{time}_i \\times u_i\n$$\n\nwhere $\\text{time}_i$ is the expected months in state $i$ and $u_i$ is its\nEQ-5D utility. The two treatment arms are evaluated on the same 60-month\nhorizon, allowing a direct QALY comparison from the patient's perspective.\n\n\nHealth state utility values (HSUVs) map each model state to a preference-based\nquality-of-life weight on the 0–1 scale (0 = death, 1 = perfect health).\nThe weights below are EQ-5D-based defaults drawn from the published literature.\nS6 (NED) carries the highest utility among living states and serves as the\nreference; a NED-normalized column (NED = 1.00) is included for sensitivity work.\n\n\n\n### Utility Values\n\nThe sources for the utility values are provided as comments in the code below. Complete references are provided in the Reference section at the end.\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Define and display utility weights\"}\n# Health state utility values (EQ-5D scale, 0 = death, 1 = perfect health).\n# S6 (NED) is the reference (highest) living state.\n# Sources: \n# S1 de Almeida et al. 2014; Noel et al. 2015\n# S2 Sprave et al. 2022 (during-RT EQ-5D ~0.83, n=366); Truong/RTOG 0522 2017 retained for S5\n# S3 Govers et al. 2016\n# S4 Sprave et al. 2022 (during-RT EQ-5D ~0.83, n=366); Govers et al. 2016\n# S5 Truong et al. / RTOG 0522 2017 (primary); Sprave et al. 2022 adjuvant CRT data support ~0.83 but POCRT toxicity justifies retaining 0.775 — see inline note\n# S6 Noel et al. 2015 (reference state)\n# S7 Meregaglia & Cairns 2017 (systematic review confirming evidence gap; only patient EQ-5D for recurrence found is median 0.70, del Barco et al. 2016, palliative/metastatic context); 0.55 is modeller's assumption\n# S8 Convention (absorbing state)\nutility <- c(\n  S1 = 0.60,   # Surgery: acute peri-operative period\n  S2 = 0.83,   # DefinitiveRT: during 6-7 week RT course (Sprave et al. 2022, mean EQ-5D at RT completion = 0.830, n=366)\n  S3 = 0.72,   # PostOpSurveillance: recovery phase\n  S4 = 0.83,   # PORT: adjuvant RT toxicity (Sprave et al. 2022, mean EQ-5D at RT completion = 0.830, n=366)\n  S5 = 0.775, # POCRT: concurrent chemoRT (revised from 0.60). Primary source: Truong/RTOG 0522 3-month EQ-5D proxy (CIS arm 0.78, CET/CIS arm 0.77); end-of-treatment value collected but not reported in paper. Comparison: Sprave et al. (2022) adjuvant CRT cohort had baseline HI = 0.849 with no significant within-group change to RT completion, and CRT vs RT-alone did not differ at RT completion (p = 0.624); the adjuvant cohort data would support ~0.83. Value retained at 0.775 as a deliberate conservative estimate: POCRT involves high-dose cisplatin concurrent with post-surgical RT (higher toxicity than Sprave 2022 mixed RT cohort), and RTOG 0522 provides the only patient-reported utility from an actual CRT trial. A sensitivity analysis using 0.83 would narrow the Surgery vs. Def RT QALY difference by ~0.009 QALYs (0.598 months in S5).\n  S6 = 0.82,   # NED: reference state (Noel 2015)\n  S7 = 0.55,   # LR Recurrence: modeller's assumption (no directly reported mean EQ-5D for LR recurrence; Meregaglia & Cairns 2017 confirms evidence gap; only available patient EQ-5D is median 0.70 from del Barco 2016 in palliative recurrent/metastatic HNC)\n  S8 = 0.00    # Death: absorbing state\n)\n\ndf_utility <- data.frame(\n  State        = paste0(\"S\", 1:8),\n  Label        = state_labels_ii,\n  Primary_Source = c(\n    \"de Almeida (2014); Noel (2015)\",\n    \"Sprave (2022)\",\n    \"Govers (2016)\",\n    \"Sprave (2022)\",\n    \"Truong / RTOG 0522 (2017)\",\n    \"Noel (2015)\",\n    \"Modeller's assumption\",\n    \"Convention\"\n  ),\n  Utility_EQ5D = utility,\n  Utility_NED1 = round(utility / utility[\"S6\"], 3),\n  QALY_Surgery = round(time_surg * utility / 12, 3),\n  QALY_DefRT   = round(time_def  * utility / 12, 3),\n  QALY_Diff    = round((time_surg - time_def) * utility / 12, 3)\n)\nrownames(df_utility) <- NULL\n\ndf_utility |>\n  gt() |>\n  cols_label(\n    State        = \"State\",\n    Label        = \"Health State\",\n    Primary_Source = \"Primary Source\",\n    Utility_EQ5D = \"EQ-5D Utility\",\n    Utility_NED1 = \"NED-Normalised\",\n    QALY_Surgery = \"QALYs — Surgery\",\n    QALY_DefRT   = \"QALYs — Definitive RT\",\n    QALY_Diff    = \"Difference (Surg − RT)\"\n  ) |>\n  tab_style(\n    style = cell_text(weight = \"bold\"),\n    locations = cells_body(rows = State == \"S6\")\n  ) |>\n  tab_style(\n    style = cell_text(color = \"#27AE60\", weight = \"bold\"),\n    locations = cells_body(columns = QALY_Diff, rows = QALY_Diff > 0)\n  ) |>\n  tab_style(\n    style = cell_text(color = \"#C0392B\", weight = \"bold\"),\n    locations = cells_body(columns = QALY_Diff, rows = QALY_Diff < 0)\n  ) |>\n  tab_spanner(\n    label   = \"Utility\",\n    columns = c(Utility_EQ5D, Utility_NED1)\n  ) |>\n  tab_spanner(\n    label   = \"QALYs by Treatment Arm\",\n    columns = c(QALY_Surgery, QALY_DefRT, QALY_Diff)\n  ) |>\n  grand_summary_rows(\n    columns  = c(QALY_Surgery, QALY_DefRT, QALY_Diff),\n    fns      = list(Total ~ sum(.)),\n    fmt      = ~ fmt_number(., decimals = 3)\n  ) |>\n  tab_footnote(\n    footnote  = md(\"Modeller's assumption. No directly reported patient EQ-5D for LR recurrence exists; best available evidence is median 0.70 (del Barco et al. 2016, palliative/metastatic context). See Meregaglia & Cairns (2017) in References.\"),\n    locations = cells_body(columns = Primary_Source, rows = State == \"S7\")\n  ) |>\n  tab_source_note(\"NED-Normalised: utility relative to S6 NED = 1.00. QALYs = utility-weighted months / 12 over a 60-month horizon. Difference = Surgery − Definitive RT; green = Surgery advantage, red = RT advantage.\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"iilabtamqz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iilabtamqz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iilabtamqz thead, #iilabtamqz tbody, #iilabtamqz tfoot, #iilabtamqz tr, #iilabtamqz td, #iilabtamqz th {\n  border-style: none;\n}\n\n#iilabtamqz p {\n  margin: 0;\n  padding: 0;\n}\n\n#iilabtamqz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iilabtamqz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iilabtamqz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iilabtamqz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iilabtamqz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iilabtamqz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iilabtamqz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iilabtamqz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iilabtamqz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iilabtamqz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iilabtamqz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iilabtamqz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iilabtamqz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iilabtamqz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iilabtamqz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iilabtamqz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iilabtamqz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iilabtamqz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iilabtamqz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iilabtamqz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iilabtamqz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iilabtamqz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iilabtamqz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iilabtamqz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iilabtamqz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iilabtamqz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iilabtamqz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iilabtamqz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iilabtamqz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iilabtamqz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iilabtamqz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iilabtamqz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iilabtamqz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iilabtamqz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iilabtamqz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iilabtamqz .gt_left {\n  text-align: left;\n}\n\n#iilabtamqz .gt_center {\n  text-align: center;\n}\n\n#iilabtamqz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iilabtamqz .gt_font_normal {\n  font-weight: normal;\n}\n\n#iilabtamqz .gt_font_bold {\n  font-weight: bold;\n}\n\n#iilabtamqz .gt_font_italic {\n  font-style: italic;\n}\n\n#iilabtamqz .gt_super {\n  font-size: 65%;\n}\n\n#iilabtamqz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iilabtamqz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iilabtamqz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iilabtamqz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iilabtamqz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iilabtamqz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iilabtamqz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#iilabtamqz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#iilabtamqz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"State\">State</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Label\">Health State</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Primary_Source\">Primary Source</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Utility\">\n        <div class=\"gt_column_spanner\">Utility</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"QALYs by Treatment Arm\">\n        <div class=\"gt_column_spanner\">QALYs by Treatment Arm</div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Utility_EQ5D\">EQ-5D Utility</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Utility_NED1\">NED-Normalised</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"QALY_Surgery\">QALYs — Surgery</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"QALY_DefRT\">QALYs — Definitive RT</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"QALY_Diff\">Difference (Surg − RT)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"stub_1_1 State\" class=\"gt_row gt_left\">S1</td>\n<td headers=\"stub_1_1 Label\" class=\"gt_row gt_left\">Surgery</td>\n<td headers=\"stub_1_1 Primary_Source\" class=\"gt_row gt_left\">de Almeida (2014); Noel (2015)</td>\n<td headers=\"stub_1_1 Utility_EQ5D\" class=\"gt_row gt_right\">0.600</td>\n<td headers=\"stub_1_1 Utility_NED1\" class=\"gt_row gt_right\">0.732</td>\n<td headers=\"stub_1_1 QALY_Surgery\" class=\"gt_row gt_right\">0.076</td>\n<td headers=\"stub_1_1 QALY_DefRT\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"stub_1_1 QALY_Diff\" class=\"gt_row gt_right\" style=\"color: #27AE60; font-weight: bold;\">0.076</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"stub_1_2 State\" class=\"gt_row gt_left\">S2</td>\n<td headers=\"stub_1_2 Label\" class=\"gt_row gt_left\">DefinitiveRT</td>\n<td headers=\"stub_1_2 Primary_Source\" class=\"gt_row gt_left\">Sprave (2022)</td>\n<td headers=\"stub_1_2 Utility_EQ5D\" class=\"gt_row gt_right\">0.830</td>\n<td headers=\"stub_1_2 Utility_NED1\" class=\"gt_row gt_right\">1.012</td>\n<td headers=\"stub_1_2 QALY_Surgery\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"stub_1_2 QALY_DefRT\" class=\"gt_row gt_right\">0.208</td>\n<td headers=\"stub_1_2 QALY_Diff\" class=\"gt_row gt_right\" style=\"color: #C0392B; font-weight: bold;\">-0.208</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"stub_1_3 State\" class=\"gt_row gt_left\">S3</td>\n<td headers=\"stub_1_3 Label\" class=\"gt_row gt_left\">PostOpSurveillance</td>\n<td headers=\"stub_1_3 Primary_Source\" class=\"gt_row gt_left\">Govers (2016)</td>\n<td headers=\"stub_1_3 Utility_EQ5D\" class=\"gt_row gt_right\">0.720</td>\n<td headers=\"stub_1_3 Utility_NED1\" class=\"gt_row gt_right\">0.878</td>\n<td headers=\"stub_1_3 QALY_Surgery\" class=\"gt_row gt_right\">0.718</td>\n<td headers=\"stub_1_3 QALY_DefRT\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"stub_1_3 QALY_Diff\" class=\"gt_row gt_right\" style=\"color: #27AE60; font-weight: bold;\">0.718</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"stub_1_4 State\" class=\"gt_row gt_left\">S4</td>\n<td headers=\"stub_1_4 Label\" class=\"gt_row gt_left\">AdjuvantRT_PORT</td>\n<td headers=\"stub_1_4 Primary_Source\" class=\"gt_row gt_left\">Sprave (2022)</td>\n<td headers=\"stub_1_4 Utility_EQ5D\" class=\"gt_row gt_right\">0.830</td>\n<td headers=\"stub_1_4 Utility_NED1\" class=\"gt_row gt_right\">1.012</td>\n<td headers=\"stub_1_4 QALY_Surgery\" class=\"gt_row gt_right\">0.052</td>\n<td headers=\"stub_1_4 QALY_DefRT\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"stub_1_4 QALY_Diff\" class=\"gt_row gt_right\" style=\"color: #27AE60; font-weight: bold;\">0.052</td></tr>\n    <tr><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"stub_1_5 State\" class=\"gt_row gt_left\">S5</td>\n<td headers=\"stub_1_5 Label\" class=\"gt_row gt_left\">AdjuvantChemoRT_POCRT</td>\n<td headers=\"stub_1_5 Primary_Source\" class=\"gt_row gt_left\">Truong / RTOG 0522 (2017)</td>\n<td headers=\"stub_1_5 Utility_EQ5D\" class=\"gt_row gt_right\">0.775</td>\n<td headers=\"stub_1_5 Utility_NED1\" class=\"gt_row gt_right\">0.945</td>\n<td headers=\"stub_1_5 QALY_Surgery\" class=\"gt_row gt_right\">0.039</td>\n<td headers=\"stub_1_5 QALY_DefRT\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"stub_1_5 QALY_Diff\" class=\"gt_row gt_right\" style=\"color: #27AE60; font-weight: bold;\">0.039</td></tr>\n    <tr><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"stub_1_6 State\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">S6</td>\n<td headers=\"stub_1_6 Label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">NED</td>\n<td headers=\"stub_1_6 Primary_Source\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Noel (2015)</td>\n<td headers=\"stub_1_6 Utility_EQ5D\" class=\"gt_row gt_right\" style=\"font-weight: bold;\">0.820</td>\n<td headers=\"stub_1_6 Utility_NED1\" class=\"gt_row gt_right\" style=\"font-weight: bold;\">1.000</td>\n<td headers=\"stub_1_6 QALY_Surgery\" class=\"gt_row gt_right\" style=\"font-weight: bold;\">1.970</td>\n<td headers=\"stub_1_6 QALY_DefRT\" class=\"gt_row gt_right\" style=\"font-weight: bold;\">2.429</td>\n<td headers=\"stub_1_6 QALY_Diff\" class=\"gt_row gt_right\" style=\"font-weight: bold; color: #C0392B;\">-0.459</td></tr>\n    <tr><th id=\"stub_1_7\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"stub_1_7 State\" class=\"gt_row gt_left\">S7</td>\n<td headers=\"stub_1_7 Label\" class=\"gt_row gt_left\">LR_Recurrence</td>\n<td headers=\"stub_1_7 Primary_Source\" class=\"gt_row gt_left\">Modeller's assumption<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></td>\n<td headers=\"stub_1_7 Utility_EQ5D\" class=\"gt_row gt_right\">0.550</td>\n<td headers=\"stub_1_7 Utility_NED1\" class=\"gt_row gt_right\">0.671</td>\n<td headers=\"stub_1_7 QALY_Surgery\" class=\"gt_row gt_right\">0.188</td>\n<td headers=\"stub_1_7 QALY_DefRT\" class=\"gt_row gt_right\">0.260</td>\n<td headers=\"stub_1_7 QALY_Diff\" class=\"gt_row gt_right\" style=\"color: #C0392B; font-weight: bold;\">-0.072</td></tr>\n    <tr><th id=\"stub_1_8\" scope=\"row\" class=\"gt_row gt_left gt_stub\"></th>\n<td headers=\"stub_1_8 State\" class=\"gt_row gt_left\">S8</td>\n<td headers=\"stub_1_8 Label\" class=\"gt_row gt_left\">Death</td>\n<td headers=\"stub_1_8 Primary_Source\" class=\"gt_row gt_left\">Convention</td>\n<td headers=\"stub_1_8 Utility_EQ5D\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"stub_1_8 Utility_NED1\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"stub_1_8 QALY_Surgery\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"stub_1_8 QALY_DefRT\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"stub_1_8 QALY_Diff\" class=\"gt_row gt_right\">0.000</td></tr>\n    <tr><th id=\"grand_summary_stub_1\" scope=\"row\" class=\"gt_row gt_left gt_stub gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">Total</th>\n<td headers=\"grand_summary_stub_1 State\" class=\"gt_row gt_left gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 Label\" class=\"gt_row gt_left gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 Primary_Source\" class=\"gt_row gt_left gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 Utility_EQ5D\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 Utility_NED1\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">—</td>\n<td headers=\"grand_summary_stub_1 QALY_Surgery\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">3.043</td>\n<td headers=\"grand_summary_stub_1 QALY_DefRT\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">2.897</td>\n<td headers=\"grand_summary_stub_1 QALY_Diff\" class=\"gt_row gt_right gt_grand_summary_row gt_first_grand_summary_row gt_last_summary_row\">0.146</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"9\">NED-Normalised: utility relative to S6 NED = 1.00. QALYs = utility-weighted months / 12 over a 60-month horizon. Difference = Surgery − Definitive RT; green = Surgery advantage, red = RT advantage.</td>\n    </tr>\n  </tfoot>\n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"9\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TW9kZWxsZXLigJlzIGFzc3VtcHRpb24uIE5vIGRpcmVjdGx5IHJlcG9ydGVkIHBhdGllbnQgRVEtNUQgZm9yIExSIHJlY3VycmVuY2UgZXhpc3RzOyBiZXN0IGF2YWlsYWJsZSBldmlkZW5jZSBpcyBtZWRpYW4gMC43MCAoZGVsIEJhcmNvIGV0IGFsLiAyMDE2LCBwYWxsaWF0aXZlL21ldGFzdGF0aWMgY29udGV4dCkuIFNlZSBNZXJlZ2FnbGlhICZhbXA7IENhaXJucyAoMjAxNykgaW4gUmVmZXJlbmNlcy4=\"><span class='gt_from_md'>Modeller’s assumption. No directly reported patient EQ-5D for LR recurrence exists; best available evidence is median 0.70 (del Barco et al. 2016, palliative/metastatic context). See Meregaglia &amp; Cairns (2017) in References.</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n\n\n### QALY Comparison by Treatment Arm\n\nWith utility weights and state occupancy times established, QALYs can be\ncompared across the two treatment arms. The stacked bar chart below shows the utility-weighted life years accrued in each health state over the 60-month horizon. Each bar is broken down by health state, so the chart reveals not just the total QALY difference between arms but *where* that difference arises. It also reveals which states contribute most of the advantages of the treatment and which states are similar for both treatments.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"QALY comparison chart\"}\n# Expected utility-weighted months per state per arm,\n# using state occupancy integrals and EQ-5D utility weights.\n# Total QALYs = sum(time_in_state_months * utility) / 12\nqaly_surg <- time_surg * utility\nqaly_def  <- time_def  * utility\n\nstate_palette <- c(\n  S1 = \"#E67E22\", S2 = \"#8E44AD\", S3 = \"#F39C12\",\n  S4 = \"#2980B9\", S5 = \"#16A085\", S6 = \"#27AE60\", S7 = \"#C0392B\"\n)\n\ndf_qaly <- data.frame(\n  State   = rep(paste0(\"S\", 1:8), 2),\n  Label   = rep(state_labels_ii, 2),\n  Arm     = rep(c(\"Surgery\", \"Definitive RT\"), each = 8),\n  QALY_mo = c(qaly_surg, qaly_def)\n) |>\n  dplyr::filter(State != \"S8\") |>\n  dplyr::mutate(\n    State = factor(State, levels = paste0(\"S\", 1:7)),\n    Arm   = factor(Arm,   levels = c(\"Surgery\", \"Definitive RT\"))\n  )\n\ntotals_label <- data.frame(\n  Arm   = factor(c(\"Surgery\", \"Definitive RT\"),\n                 levels = c(\"Surgery\", \"Definitive RT\")),\n  total = c(sum(qaly_surg), sum(qaly_def)) / 12,\n  label = paste0(round(c(sum(qaly_surg), sum(qaly_def)) / 12, 2), \" QALYs\")\n)\n\nggplot(df_qaly, aes(x = Arm, y = QALY_mo / 12, fill = State)) +\n  geom_col(width = 0.55) +\n  geom_text(\n    data        = totals_label,\n    aes(x = Arm, y = total + 0.06, label = label),\n    inherit.aes = FALSE,\n    fontface    = \"bold\", size = 4\n  ) +\n  scale_fill_manual(\n    values = state_palette,\n    labels = setNames(state_labels_ii[1:7], paste0(\"S\", 1:7))\n  ) +\n  scale_y_continuous(\n    expand = expansion(mult = c(0, 0.08)),\n    breaks = seq(0, 3, 0.5)\n  ) +\n  labs(\n    x        = NULL,\n    y        = \"Quality-Adjusted Life Years (QALYs)\",\n    fill     = \"Health State\",\n    title    = \"Expected QALYs by Health State and Treatment Arm\",\n    subtitle = \"60-month horizon; utility weights from EQ-5D literature defaults\",\n    caption  = \"State S8 (Death, utility = 0) excluded; contributes 0 QALYs\"\n  ) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n#### A few things worth noting from the chart:\n\n* Surgery accumulates 3.04 QALYs vs. 2.9 QALYs for Definitive RT over the 60-month horizon — a difference of ~0.14 QALYs.\n* The dominant contributor in both arms is NED (green), which is expected given its high utility (0.82) and long sojourn time.\n* Surgery's advantage comes largely from the PostOpSurveillance (orange) segment, which has a better utility (0.72) than Definitive RT's LR Recurrence (dark red) burden.\n* The LR Recurrence segment is visibly larger for the Definitive RT arm (0.26 QALYs vs. 0.19), consistent with the higher recurrence probability built into that arm's jump chain.\n* These QALY estimates are model-based (from Q_base × utility) and do not yet incorporate cost.\n\n## Discussion\n\nThe intended users of the class of models I am proposing are physicians and their support teams who are making decisions about patient treatments and explaining the possible consequences of the treatments to their patients. In the first use case, physicians may find the formality of the model and its baseline estimates useful in finalizing their decisions and documenting their decision making process. Having a model to inform treatment decisions should be especially helpful in situations where multiple physicians collaborate on deciding treatment options. At the very least a model would be useful in verifying shared assumptions.\n\nThe second use of the model to help physicians and their care teams communicate with patients about the consequences of various treatment options is more speculative. But at the very least the exercise of explaining a journey through various states and interpreting the QALY's may be useful in structuring patient conversations and setting expectations. \n\n## Technical Notes\n\n\n### Five year adjustment process\nFive-year background survival for the general US population at age 62, $S^{(5)}_{62}$,\nis computed from the [2021 SSA Period Life Table](https://www.ssa.gov/oact/STATS/table4c6_2021_TR2024.html) as the product of annual survival probabilities across ages 62 to 66:\n\n$$S^{(5)}_{62} = \\prod_{x=62}^{66}(1 - q_x)$$\n\nwhere $q_x$ is the one-year death probability at exact age $x$ (SSA notation).\nUsing the 2021 table values for ages 62–66:\n$q_x^{\\text{male}}$ = 0.01648, 0.01762, 0.01876, 0.01991, 0.02110 and\n$q_x^{\\text{female}}$ = 0.01014, 0.01085, 0.01155, 0.01222, 0.01295,\ngiving $S^{(5)}_{62} = 0.910$ (male) and $0.944$ (female).\nThe sex-weighted background survival is:\n\n$$\\bar{S}^{(5)} = w_M \\cdot S^{(5)}_M + w_F \\cdot S^{(5)}_F\n= 0.70 \\times 0.910 + 0.30 \\times 0.944 = 0.920$$\n\nwhere the 70:30 sex split is from SEER oral cavity incidence data.\nAbsolute five-year OS is then obtained as:\n\n$$\\text{OS}_{\\text{abs}} = r \\times \\bar{S}^{(5)} = 0.84 \\times 0.920 = 0.773$$\n\nwhere $r = 0.84$ is the SEER five-year relative survival for localised oral cavity cancer\n(Siegel et al. 2024, *CA Cancer J Clin*, Figure 5). The code below details this calculation\nand provides a sensitivity check at age 65 (note: age-65 values are pending verification).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Siegel 2024: relative → absolute OS derivation\"}\n# US Social Security Administration period life tables (2021 release, used for 2019 SEER cohort).\n# 5-year survival probabilities by sex at age 62 (closest to OSCC median diagnosis age).\n# Computed as prod(1 - q_x) for x = 62:66 from Table 4c6 (2021 Trustees Report cycle).\n# Source: Social Security Administration. Period Life Table, 2021 (2024 Trustees Report).\n# https://www.ssa.gov/oact/STATS/table4c6.html\nsurv_male_62   <- 0.9096  # 5-yr background survival, males age 62;   SSA 2021 prod(1-qx), x=62:66\nsurv_female_62 <- 0.9436  # 5-yr background survival, females age 62; SSA 2021 prod(1-qx), x=62:66\n\n# OSCC sex distribution: ~70% male, ~30% female (SEER, oral cavity)\nprop_male <- 0.70\nexpected_survival_5yr <- prop_male * surv_male_62 + (1 - prop_male) * surv_female_62\n\n# SEER 5-year relative survival for localised oral cavity (Siegel 2024, Fig. 5)\nrelative_survival_5yr <- 0.84\n\n# Absolute OS = relative survival × expected (background) survival\nabsolute_os_5yr <- relative_survival_5yr * expected_survival_5yr\n\n# Sensitivity: 5-yr background survival at age 65 (upper end of median diagnosis age range).\n# Source: Social Security Administration. Period Life Table, 2021 (2024 Trustees Report).\n# Computed as prod(1 - q_x) for x = 65:69. https://www.ssa.gov/oact/STATS/table4c6.html\nsurv_male_65   <- 0.8923  # 5-yr background survival, males age 65;   SSA 2021 prod(1-qx), x=65:69\nsurv_female_65 <- 0.9320  # 5-yr background survival, females age 65; SSA 2021 prod(1-qx), x=65:69\nexpected_surv_65 <- prop_male * surv_male_65 + (1 - prop_male) * surv_female_65\nabsolute_os_65   <- relative_survival_5yr * expected_surv_65\n\ndata.frame(\n  Assumption              = c(\"Age 62 (lower bound)\", \"Age 65 (upper bound)\"),\n  Background_5yr_survival = round(c(expected_survival_5yr, expected_surv_65), 3),\n  Absolute_5yr_OS         = round(c(absolute_os_5yr, absolute_os_65), 3)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Assumption Background_5yr_survival Absolute_5yr_OS\n1 Age 62 (lower bound)                   0.920           0.773\n2 Age 65 (upper bound)                   0.904           0.760\n```\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Siegel 2024: relative → absolute OS derivation\"}\n# Age 62: background survival 0.920 × relative survival 0.84 = 0.773 (~77%).\n# Age 65 sensitivity: background survival 0.904 × relative survival 0.84 = 0.760 (~76%).\n```\n:::\n\n\n### Using the code with Real Data\n\nThere is no doubt that models based on real patient data would be more convincing. To this end, I have structured the format of the generated synthetic data file so that it is suitable for fitting a continuous time Markov chain using the `R` package `msm`. I have verified that `msm` is able to fit the eight state sample model from the synthetic data. It is reasonable to expect that models of similar complexity could be fit from real patient data.\n\n\n## References\n\nThe references in this section are neither complete nor definitive. The literature is enormous. They have been selected to support the default values for the user inputs.\n\n### References for Background Mortality\n\n* Social Security Administration. *Period Life Table, 2021* (as used in the 2024 Trustees Report).\n  Available at: <https://www.ssa.gov/oact/STATS/table4c6.html>. Accessed 2026-03-18.\n  Five-year background survival probabilities for the general US population at ages 62 and 65,\n  computed as $S^{(5)} = \\prod_{x}^{x+4}(1-q_x)$ where $q_x$ is the one-year death probability\n  at exact age $x$. Values at age 62: male $S^{(5)} = 0.910$, female $S^{(5)} = 0.944$.\n  Used to convert SEER relative survival (Siegel 2024) to absolute OS for the calibration benchmark.\n  Values at age 65: male $S^{(5)} = 0.892$, female $S^{(5)} = 0.932$\n  (computed from $q_{65}$–$q_{69}$ = 0.01991, 0.02110, 0.02242, 0.02385, 0.02536 male;\n   0.01222, 0.01295, 0.01384, 0.01486, 0.01603 female).\n\n### References for Transition Probabilities and Sojourn Times\n\n* [Bernier et al. (2004)](https://pubmed.ncbi.nlm.nih.gov/15128894/) \"Postoperative Irradiation with or without Concomitant Chemotherapy for Locally Advanced Head and Neck Cancer\", *N Engl J Med.* 350:1945–1952. PMID: 15128894. Landmark EORTC 22931 RCT establishing concurrent chemoRT as standard of care for high-risk post-operative HNSCC. Supports jump_P[5,6] and the locoregional control rates in the POCRT arm (S5).\n\n* [Blatt et al. (2022)](https://doi.org/10.3390/jcm11237061) \"Tumor Recurrence and Follow-Up Intervals in Oral Squamous Cell Carcinoma\", *J Clin Med.* 11(23):7061. PMID: 36498636. PMC: PMC9740063. DOI: 10.3390/jcm11237061. University Medical Centre Mainz, n = 760 OSCC patients. Supports S3 NED declaration timing ~24 months (mean recurrence interval 24 ± 26 months; 50% of recurrences by 24 months) and S3 mean sojourn revision to 22 months.\n\n* [Brands et al. (2019)](https://onlinelibrary.wiley.com/doi/10.1002/cam4.2124) \"Time Patterns of Recurrence and Second Primary Tumors in a Large Cohort of Patients Treated for Oral Cavity Cancer\", *Cancer Med.* 8(12):5810–5819. DOI: 10.1002/cam4.2124. Retrospective cohort of 594 OSCC patients; the great majority of recurrences occur in the first 2 years; 5-year cumulative second-event risk ~30%. Supports S3 sojourn revision to 22 months and S6 NED calibration.\n\n* [Contrera et al. (2022)](https://pubmed.ncbi.nlm.nih.gov/36155359/) \"Outcomes for Recurrent Oral Cavity Squamous Cell Carcinoma\", *Oral Oncol.* 134:106127. PMID: 36155359. DOI: 10.1016/j.oraloncology.2022.106127. MD Anderson, n = 259 salvage surgeries (1997-2011); 5-year OS 44.2% for surgical candidates vs. 1.5% for nonsurgical therapy; 51% second recurrence at median 17 months. Provides contextual support for the salvage surgery framework; primary source for current values jump_P[7,6] = 0.43 and jump_P[7,8] = 0.57 is Lee et al. (2024).\n\n* [Cooper et al. (2004)](https://www.nejm.org/doi/full/10.1056/NEJMoa032646) \"Postoperative Concurrent Radiotherapy and Chemotherapy for High-Risk Squamous-Cell Carcinoma of the Head and Neck\", *N Engl J Med.* 350:1937–1944. PMID: 15084618. RTOG 9501 RCT; locoregional control ~60% at 5 years in the concurrent chemoRT arm. Supports S5 jump probabilities.\n\n* [Correia et al. (2026)](https://doi.org/10.1002/lio2.70363) \"Timely Matters: Predictors of Delay in Oral Cavity Cancer Patients Across the Care Continuum\". *Laryngoscope Investig Otolaryngol.* 11(2):e70363. DOI: 10.1002/lio2.70363. (Also available via [eScholarship](https://escholarship.org/uc/item/9680b1bw). n = 93 OCSCC patients. Median surgery-to-adjuvant RT interval 8.4 weeks (same institution) and 9.3 weeks (different facility). Supports S1 mean sojourn revision to 1.5 months.\n\n* [Dayan et al. (2023)](https://doi.org/10.1016/j.oraloncology.2023.106622) \"Predictors of prolonged treatment time intervals in oral cavity cancer\", *Oral Oncol.* 106622. DOI: 10.1016/j.oraloncology.2023.106622. CHUM Montreal, n = 145 multimodal OCSCC patients. Median surgery-to-PORT interval 64 days = 2.1 months. Supports S1 mean sojourn revision. \n\n* [Goodwin (2000)](https://onlinelibrary.wiley.com/doi/10.1097/00005537-200003001-00001) \"Salvage Surgery for Patients with Recurrent Squamous Cell Carcinoma of the Upper Aerodigestive Tract: When Do the Ends Justify the Means?\", *Laryngoscope.* 110(suppl 93):1–18. Cited in v2 for salvage success rate 15–25%. Superseded in v3 by Lee et al. 2024 for jump_P[7,6]; retained for historical context.\n\n* [Graboyes et al. (2017)](https://acsjournals.onlinelibrary.wiley.com/doi/10.1002/cncr.30651) \"Adherence to National Comprehensive Cancer Network Guidelines for Time to Initiation of Postoperative Radiation Therapy for Patients with Head and Neck Cancer\", *Cancer.* 123(14):2651–2660. DOI: 10.1002/cncr.30651. NCDB analysis, n = 47,273 HNSCC patients; over 50% failed to initiate PORT within the NCCN-recommended 6 weeks. Supports real-world S1 mean sojourn estimate of 1.5 months.\n\n* [Hosni et al. (2019)](https://doi.org/10.1016/j.ijrobp.2018.09.013) \"Predictors of Early Recurrence Prior to Planned Postoperative Radiation Therapy for Oral Cavity Squamous Cell Carcinoma and Outcomes Following Salvage Intensified Radiation Therapy\", *Int J Radiat Oncol Biol Phys.* 103(2):363–373. PMID: 30244160. Princess Margaret Cancer Centre, n = 601 OSCC patients (2003–2015); 3-year OS ~71% (95% CI 67–75%) after adjuvant PORT. Supports S4 jump probabilities (jump_P[4, 6:8]).\n\n\n* [Katsoulakis et al. (2018)](https://doi.org/10.1002/lary.27191) \"Long-term outcomes in oral cavity squamous cell carcinoma with adjuvant and salvage radiotherapy after surgery\", *Laryngoscope.* PMID: 29637571. DOI: 10.1002/lary.27191. Memorial Sloan Kettering / VA Tampa; Evangelia Katsoulakis (first author). Provides contextual reference for the adjuvant RT pathway; jump_P[2,6] is now sourced from Dana-Farber Group 2011 and Studer et al. 2007 above.\n\n* [Lee et al. (2024)](https://pubmed.ncbi.nlm.nih.gov/39243149/) \"Clinical Outcome of Salvage Surgery in Patients with Recurrent Oral Cavity Cancer: A Systematic Review and Meta-Analysis\", *Head Neck.* 46(11):2901–2909. PMID: 39243149. DOI: 10.1002/hed.27928. 14 retrospective cohort studies, n = 2,069; pooled 5-year OS after salvage surgery = 43.0%; late-relapse subgroup 63.8% vs. 30.0% for early relapse. Primary source for jump_P[7,6] = 0.43 (salvage success) and jump_P[7,8] = 0.57 (mortality); revised from 0.25/0.75 — previous values over-estimated post-recurrence mortality relative to this pooled estimate.\n\n* [Liu et al. (2007)](https://pubmed.ncbi.nlm.nih.gov/17210345/) \"Impact of Recurrence Interval on Survival of Oral Cavity Squamous Cell Carcinoma Patients after Local Relapse\", *Otolaryngol Head Neck Surg.* 136(1):112–118. PMID: 17210345. DOI: 10.1016/j.otohns.2006.07.002. n = 1,687 oral cancer patients; 5-year OS after local recurrence 31.56%; recurrence within 18 months predicted higher mortality. Supports S7 sojourn of 12.5 months.\n\n* [Mehanna et al. (2016)](https://www.nejm.org/doi/full/10.1056/NEJMoa1514493) \"PET-CT Surveillance versus Neck Dissection in Advanced Head and Neck Cancer\", *N Engl J Med.* 374(15):1444–1454. PMID: 26958921. DOI: 10.1056/NEJMoa1514493. PET-NECK RCT, n = 564 patients; response imaging performed at 12 weeks post-chemoradiotherapy; established ≥12-week post-RT interval as standard for response assessment in HNSCC. Supports S2 mean sojourn of 3.0 months (RT course 1.5 mo + ≥12-week response assessment window).\n\n* [Luryi et al. (2014)](https://journals.sagepub.com/doi/abs/10.1177/0194599814551718) \"Positive Surgical Margins in Early Stage Oral Cavity Cancer: An Analysis of 20,602 Cases\", *Otolaryngol Head Neck Surg.* 151(6):984–990. PMID: 25210849. Large NCDB analysis of surgical margin rates and downstream outcomes in early-stage oral cavity cancer; early-stage N0 patients with negative margins have materially lower recurrence rates than all-stage series. Supports S3 transition probability framework, jump_P[3,7] = 0.18, and S6 NED calibration to 120 months.\n\n* [Nathan et al. (2025)](https://doi.org/10.18203/issn.2454-5929.ijohns20252980) \"The Influence of Reconstruction following Hemiglossectomy on Perioperative Outcomes\", *Int J Otorhinolaryngol Head Neck Surg.* DOI: 10.18203/issn.2454-5929.ijohns20252980. NSQIP database study, n = 866 hemiglossectomy patients (2008–2022); consistent with ~1–2% 30-day mortality in modern series. Supports jump_P[1,8] = 0.015.\n\n\n\n* [Ord, Kolokythas & Reynolds (2006)](https://pubmed.ncbi.nlm.nih.gov/16916677/) \"Surgical Salvage for Local and Regional Recurrence in Oral Cancer\", *J Oral Maxillofac Surg.* 64(9):1409–1414. PMID: 16916677. DOI: 10.1016/j.joms.2006.05.026. Reports outcomes of surgical salvage in recurrent oral cancer; data on local and regional recurrence rates and survival after primary surgery. Supports jump_P[3,7] = 0.18 (LR recurrence 12–18% for Stage II) and S3 mean sojourn revision to 22 months. \n\n* [Sher et al. (2011)](https://www.sciencedirect.com/science/article/pii/S0360301611003245) \"Treatment of Oral Cavity Squamous Cell Carcinoma with Adjuvant or Definitive Intensity-Modulated Radiation Therapy\", *Int J Radiat Oncol Biol Phys.* 2011. PMID: 21531515. Dana-Farber Cancer Institute; n = 42 OCSCC (30 adjuvant IMRT, 12 definitive IMRT); Stage I–IV (24% Stage II); 2-yr LRC for definitive IMRT = 64%, 2-yr OS = 63%. Corroborated by Studer G, Zwahlen RA, Graetz KW et al. (2007), \"IMRT in oral cavity cancer\", *Radiat Oncol.* 2:16. PMID: 17430599. DOI: 10.1186/1748-717X-2-16. University Hospital Zurich; n = 58 OCC IMRT patients; T1 LC = 95%; T2–4 and recurred stages LC ~50–60% at 2 years; definitive IMRT LC = 43% (but cohort was 69% T3/4 or recurred). **Primary reference pair for jump_P[2,6] = 0.65** — definitive RT arm locoregional control for T2N0M0 Stage II; value is consistent with the early-stage subgroup in both series.\n\n\n* [Shetty et al. (2022)](https://pmc.ncbi.nlm.nih.gov/articles/PMC8831824/) \"Salvage Surgery in Recurrent Oral Squamous Cell Carcinoma\", *Front Oral Health.* PMC8831824. Review of salvage surgery outcomes; radiation-naive recurrent OCSCC after salvage surgery: 5-year OS 59%, recurrence-free survival 60%. Provides supporting context for the salvage surgery framework; current value jump_P[7,6] = 0.43 is sourced from Lee et al. (2024).\n\n* [Siegel et al. (2024)](https://doi.org/10.3322/caac.21820) \"Cancer Statistics, 2024\", *CA Cancer J Clin.* 74(1):12–49. PMID: 38230766. DOI: 10.3322/caac.21820. Annual American Cancer Society SEER-based statistics report. Figure 5 reports 5-year relative survival for localized oral cavity cancer (SEER localised stage, encompassing Stage I–II) as approximately 84% (diagnoses 2013–2019, follow-up through 2020). Note: relative survival overstates absolute OS — adjusting for sex-weighted background mortality from the SSA 2021 Period Life Table at median age 62 ($\\\\bar{S}^{(5)} = 0.920$) yields an estimated absolute 5-yr OS of approximately 77% ($0.84 \\\\times 0.920 = 0.773$) for Stage II localised oral cavity. Used as the primary population-level calibration benchmark for the Surgery arm.\n\n* [Szturz et al. (2017)](https://pubmed.ncbi.nlm.nih.gov/28533474/) \"Weekly Low-Dose Versus Three-Weekly High-Dose Cisplatin for Concurrent Chemoradiation in Locoregionally Advanced Non-Nasopharyngeal Head and Neck Cancer: A Systematic Review and Meta-Analysis\", *Oncologist.* 22(9):1056–1066. PMID: 28533474. \n\n* [Tam et al. (2017)](https://jamanetwork.com/journals/jamaotolaryngology/fullarticle/2618943) \"Estimating Survival After Salvage Surgery for Recurrent Oral Cavity Cancer\", *JAMA Otolaryngol Head Neck Surg.* 143(7):685–690. PMID: 28448645. Reports survival outcomes following salvage surgery for recurrent oral cavity SCC. Supports S7 transition structure.\n\n* [Tassone et al. (2023)](https://doi.org/10.1002/ohn.205) \"Going Off Guidelines: An NCDB Analysis of Missed Adjuvant Therapy Among Surgically Treated Oral Cavity Cancer\", *Otolaryngol Head Neck Surg.* 169(3):632–641. PMID: 36939392. DOI: 10.1002/ohn.205. NCDB analysis, n = 53,503; establishes PORT vs. POCRT indications and allocation rates. Supports jump_P[1,4] = 0.25 and jump_P[1,5] = 0.15.\n\n* [Temam et al. (2005)](https://onlinelibrary.wiley.com/doi/abs/10.1002/hed.20234) \"Treatment of the N0 Neck during Salvage Surgery after Radiotherapy of Head and Neck Squamous Cell Carcinoma\", *Head Neck.* 27(8):653–658. Cited in v2 for salvage success rates. Superseded in v3 by Lee et al. 2024; retained for historical context.\n\n### References for EQ-5D Utilities\n\n* [de Almeida et al. (2014)](https://onlinelibrary.wiley.com/doi/abs/10.1002/hed.23340) \"Preferences and Utilities for Health States after Treatment for Oropharyngeal Cancer: Transoral Robotic Surgery versus Definitive (Chemo)radiotherapy\", *Head Neck.* 36(4):529–539. Reports EQ-5D utility values across treatment modalities; informs utility weights for treatment and NED states.\n\n* [Govers et al. (2016)](https://onlinelibrary.wiley.com/doi/abs/10.1111/coa.12502) \"Quality of Life after Different Procedures for Regional Control in Oral Cancer Patients: Cross-Sectional Survey\", *Clin Otolaryngol.* 41(3):228–235. EQ-5D-3L measurement in oral cavity OSCC patients following different regional treatment approaches.\n\n* [Meregaglia & Cairns (2017)](https://doi.org/10.1186/s12955-017-0748-z) \"A Systematic Literature Review of Health State Utility Values in Head and Neck Cancer\", *Health Qual Life Outcomes.* 15(1):174. DOI: 10.1186/s12955-017-0748-z. PMID: 28865475. Systematic review of 28 studies and 346 health state utility values in HNC; recommends EQ-5D as the preferred instrument. Confirms that evidence for recurrent and metastatic HNC states is sparse: the only patient-reported EQ-5D for recurrence found in the review is a median of 0.70 (del Barco et al. 2016), from a palliative-intent recurrent/metastatic cohort — a different clinical context from S7 (locoregional recurrence with potential salvage intent) in this model. The S7 utility of 0.55 is a modeller's assumption informed by this evidence gap, not a directly reported value from this review.\n\n* [Noel et al. (2015)](https://jamanetwork.com/journals/jamaotolaryngology/fullarticle/2397443#:~:text=Design%2C%20Setting%2C%20and%20Participants%20In,Mark%203%20(HUI3)%20questionnaire.) \"Comparison of Health State Utility Measures in Patients With Head and Neck Cancer\", *JAMA Otolaryngol Head Neck Surg.* 141(8):696–703. Prospective, cross-sectional, and longitudinal study of 100 patients with squamous cell carcinoma of the upper aerodigestive tract. Mean EQ-5D-5L = 0.82 three months post-treatment with no evidence of recurrence. Primary source for NED (S6) utility value.\n\n* [Ramaekers et al. (2011)](https://doi.org/10.1016/j.oraloncology.2011.05.012) \"The Impact of Late Treatment-Toxicity on Generic Health-Related Quality of Life in Head and Neck Cancer Patients after Radiotherapy\", *Oral Oncol.* 47(8):768–774. DOI: 10.1016/j.oraloncology.2011.05.012. Multi-centre cross-sectional survey; EQ-5D measured in HNC patients **at least 6 months post-RT** (late-effects survivorship cohort, not active treatment). Reports xerostomia and dysphagia as independent predictors of reduced utility post-RT. Retained as contextual reference for late RT toxicity; **not** the primary source for S4 (PORT) utility — that cohort does not represent patients during active adjuvant radiotherapy.\n* [Sprave et al. (2022)](https://doi.org/10.1186/s12885-022-10346-4) \"Patient Reported Outcomes Based on EQ-5D-5L Questionnaires in Head and Neck Cancer Patients: A Real-World Study\", *BMC Cancer* 22:1236. DOI: 10.1186/s12885-022-10346-4. PMID: 36447175. Freiburg University; n = 366 H&N cancer patients undergoing modern RT; prospective real-world PRO study; mean EQ-5D-5L at end of RT = 0.830 (SD not reported for full cohort). **Primary source for S2 (Definitive RT) and S4 (PORT) utility weights = 0.83.** Corroborated by Sprave et al. (2020, n=49): mean EQ-5D at RT completion = 0.828.\n* [Sprave et al. (2020)](https://doi.org/10.1080/14737167.2020.1823220) \"Characterization of Health-Related Quality of Life Based on the EQ-5D-5L Questionnaire in Head-and-Neck Cancer Patients Undergoing Modern Radiotherapy\", *Expert Rev Pharmacoecon Outcomes Res.* 20(6):673–682. DOI: 10.1080/14737167.2020.1823220. PMID: 32912005. Freiburg University Medical Center; n = 49 H&N cancer patients (57% definitive, 41% adjuvant RT); mean EQ-5D-5L at RT completion = 0.828 (SD 0.16). Corroborates Sprave 2022; supports S4 utility revision. Note: no significant permanent HRQOL deterioration observed at 6-month follow-up.\n\n* [Truong et al. / RTOG 0522 (2017)](https://pmc.ncbi.nlm.nih.gov/articles/PMC5303682/) \"Quality of Life and Performance Status from a Substudy Conducted Within a Prospective Phase 3 Randomized Trial of Concurrent Accelerated Radiation Plus Cisplatin With or Without Cetuximab for Locally Advanced Head and Neck Carcinoma: NRG Oncology RTOG 0522\", *Int J Radiat Oncol Biol Phys.* 97(4):687–699. PMC5303682. PMID: 27727066. DOI: 10.1016/j.ijrobp.2016.08.003. Prospective phase III RCT, n = 818 analyzable patients (oropharynx, hypopharynx, larynx; Stage III–IV); EQ-5D-3L collected at pretreatment, last 2 weeks of treatment, 3 months, and annually. **Reported EQ-5D values:** baseline ~0.79 (CIS 0.78, CET/CIS 0.80); at 3 months from treatment start ~0.775 (CIS 0.78, CET/CIS 0.77); at 1 year ~0.84. **Note: the EQ-5D value for the 'within last 2 weeks of treatment' time point was collected but not reported in the paper** — the authors identified omission of an acute FACT-HN assessment as a study limitation. The 3-month value (0.775) is used as the closest available proxy for active-treatment utility in S5 (POCRT). Secondary limitation: cohort is definitively treated oropharynx/larynx (not postoperative oral cavity POCRT); adopted as best available CRT utility source. **Comparison with Sprave et al. (2022):** the Sprave 2022 adjuvant CRT cohort (baseline HI = 0.849, stable to RT completion; CRT vs RT-alone not significantly different at RT completion, p = 0.624) would support a value of ~0.83 for S5. The RTOG 0522-derived value of 0.775 is retained as a conservative estimate reflecting the higher toxicity of POCRT (high-dose cisplatin, post-surgical) relative to the mixed Sprave 2022 cohort. A sensitivity analysis using 0.83 would reduce the Surgery vs. Def RT QALY difference by ~0.009 QALYs. **Primary source for S5 (POCRT) utility = 0.775.** Not the primary source for S2 (RT alone); see Sprave et al. (2022).\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}